/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mgw.main;

import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import mgw.gameplay.Skill;

/**
 *
 * @author mejap
 */
public class Card extends javax.swing.JPanel {

    /**
     * Creates new form Card
     */
    public Skill skill;
    boolean clicked = false;
    Icon img;
    static int counter = 1;
    public Card(Skill skill) {
        this.skill = skill;
        initComponents();
        background.setBackground(new Color(0,0,0));
        img = new javax.swing.ImageIcon(getClass().getResource("/mgw/main/imgdeck/" + counter++ + ".png"));
        gambar.setIcon(img);
    }

    public Card() {
    }
    
    public javax.swing.ImageIcon getIcon() {
        return (ImageIcon) gambar.getIcon();
    }
    
    public void setIconNull(){
        gambar.setOpaque(false);
    }
    public void cardClicked(){
        clicked = true;
        gambar.setIcon(null);
    }
    public void deckClicked(){
        clicked = false;
        gambar.setIcon(img);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gambar = new javax.swing.JLabel();
        background = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(100, 100));
        setLayout(new java.awt.CardLayout());

        gambar.setPreferredSize(new java.awt.Dimension(114, 114));
        add(gambar, "card2");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );

        background.setBackground(new Color(0,0,0,100));

        add(background, "card3");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel gambar;
    // End of variables declaration//GEN-END:variables
}
