/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mgw.main;

import java.io.Serializable;
import javax.swing.Icon;
import mgw.gameplay.Skill;

/**
 *
 * @author user
 */
public class Deck extends javax.swing.JPanel implements Serializable {

    /**
     * Creates new form Deck
     */
    boolean empty;
    Skill skill;
    public Deck() {
        initComponents();
        empty = true;
        skill = null;
    }
    public Deck(Skill s){
        initComponents();
        empty = false;
        skill = s;
        jLabel1.setIcon(s.img);
    }
    public void setNull(){
        if(skill != null)jLabel1.setIcon(skill.back);
    }
    public void reset(){
        if(skill != null)jLabel1.setIcon(skill.img);
    }
    public void deckCopy(SkillCard c, Account active){
        empty = false;
        skill = c.skill;
        jLabel1.setIcon(c.img);
        active.counter++;
        c.cardClicked();
    }
    
    public void deckRemove(SkillCard [] card, Account active){
        for(SkillCard i : card){
            if(i.skill.equals(skill)){
                System.out.println(i.skill.equals(skill));
                empty = true;
                skill = null;
                jLabel1.setIcon(null);
                active.counter--;
                i.deckClicked();
                return;
            }
        }
    }
    
    public Icon jlabel1(){
        return jLabel1.getIcon();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
class Deck2 extends javax.swing.JPanel{
    public javax.swing.JLabel jLabel;
    boolean available = true;
    Skill skill = null;
    static int counter = 0;
    public Deck2() {
        initComponents();
    }
   
    public void setLogo(Icon i){
        jLabel.setIcon(i);
    }
    public void setSkill(Skill i){
        jLabel.setIcon(i.img);
        setSize(114, 114);
    }
    /*public void deckCopy(SkillCard d){
        jLabel.setIcon(d.img);
        skill = d.skill;
        counter++;
    }
    public void deckRemove(SkillCard [] card){
        for(SkillCard i : card){
            if(i.skill.equals(skill)){
                counter--;
                skill = null;
                jLabel.setIcon(null);
                return;
            }
        }
    }*/
    private void initComponents() {

        jLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel)
        );
    }
    
    
}