/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mgw.main;

import javax.swing.Icon;
import mgw.gameplay.Skill;

/**
 *
 * @author user
 */
public class Deck extends javax.swing.JPanel {

    /**
     * Creates new form Deck
     */
    boolean empty = true;
    Skill skill = null;
    static int counter = 0;
    public Deck() {
        initComponents();
        //jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mgw/main/" + counter++ + ".png")));
        //jlabel1();
    }
    public void deckCopy(SkillCard c){
        empty = false;
        skill = c.skill;
        jLabel1.setIcon(c.img);
        counter++;
        c.cardClicked();
    }
    
    public void deckRemove(SkillCard [] card){
        for(SkillCard i : card){
            if(i.skill.equals(skill)){
                counter--;
                empty = true;
                skill = null;
                jLabel1.setIcon(null);
                i.deckClicked();
                return;
            }
        }
    }
    
    public Icon jlabel1(){
        return jLabel1.getIcon();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
class Deck2 extends javax.swing.JPanel{
    private javax.swing.JLabel jLabel;

    public Deck2() {
    }
    
    public Deck2(Deck d) {
        jLabel.setIcon(d.jlabel1());
    }
    public void deckCopy(Deck d){
        jLabel.setIcon(d.jlabel1());
    }
    private void initComponents() {

        jLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel)
        );
    }
    
    
}