/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mgw.main;

import mgw.gameplay.Skill;

/**
 *
 * @author user
 */
public class Deck extends javax.swing.JPanel {

    /**
     * Creates new form Deck
     */
    boolean empty = true;
    Skill skill = null;
    static int counter = 0;
    public Deck() {
        initComponents();
        //jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mgw/main/" + counter++ + ".png")));
        //jlabel1();
    }
    public void deckCopy(Card c){
        empty = false;
        skill = c.skill;
        jLabel1.setIcon(c.getIcon());
        counter++;
        c.cardClicked();
    }
    public void deckRemove(Card [] card){
        for(Card i : card){
            if(i.skill.equals(skill)){
                counter--;
                empty = true;
                skill = null;
                jLabel1.setIcon(null);
                i.deckClicked();
                return;
            }
        }
    }
    
    public void jlabel1(){
        //jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Ruben Data\\Kuliah\\INFORMATIKA\\Semester 2\\PBO or OOP\\Projek\\2022_PBO_P1\\cardType\\10.png"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
