/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mgw.main;

import java.awt.Color;

/**
 *
 * @author mejap
 */
public class HistoryLogPanel extends javax.swing.JPanel {

    /**
     * Creates new form HistoryLogPanel
     */
    public HistoryLogPanel(Account activeAccount, HistoryLog hl) {
        initComponents();
        if(activeAccount == hl.winner())
            this.setBackground(new Color(204,255,204));
        else
            this.setBackground(new Color(255,204,204));
        
        jp_Challenger.setText(hl.challenger().username);
        jp_Challenged.setText(hl.challenged().username);
        jp_Status.setText(activeAccount == hl.winner() ? "WON" : "LOST");
        jp_Turns.setText(Integer.toString(hl.turns()));
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_Challenger = new javax.swing.JLabel();
        jp_Challenged = new javax.swing.JLabel();
        jp_Status = new javax.swing.JLabel();
        jp_Turns = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1300, 100));

        jp_Challenger.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jp_Challenger.setForeground(new java.awt.Color(0, 0, 0));
        jp_Challenger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jp_Challenger.setText("jLabel1");

        jp_Challenged.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jp_Challenged.setForeground(new java.awt.Color(0, 0, 0));
        jp_Challenged.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jp_Challenged.setText("jLabel1");

        jp_Status.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jp_Status.setForeground(new java.awt.Color(0, 0, 0));
        jp_Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jp_Status.setText("jLabel1");

        jp_Turns.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jp_Turns.setForeground(new java.awt.Color(0, 0, 0));
        jp_Turns.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jp_Turns.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jp_Challenger, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jp_Challenged, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jp_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jp_Turns, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jp_Challenger, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp_Challenged, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp_Turns, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jp_Challenged;
    private javax.swing.JLabel jp_Challenger;
    private javax.swing.JLabel jp_Status;
    private javax.swing.JLabel jp_Turns;
    // End of variables declaration//GEN-END:variables
}
