package mgw.main;


import javax.swing.JFrame;
import java.awt.*;
import javax.swing.*;

public class Program extends javax.swing.JFrame {

    static GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
    
    /**
     * Creates new form Program
     */
    public Program() {
        this.setUndecorated(true);
        initComponents();
    }
    
    public final void fullScreen()
    {
        this.setResizable(false);
        gd.setFullScreenWindow(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jp_Background = new javax.swing.JPanel();
        jp_MainMenu = new javax.swing.JPanel();
        jl_AccountName = new javax.swing.JLabel();
        jp_PlayButton = new javax.swing.JPanel();
        jl_Play = new javax.swing.JLabel();
        jp_DeckButton = new javax.swing.JPanel();
        jl_Deck = new javax.swing.JLabel();
        jp_HelpButton = new javax.swing.JPanel();
        jl_Help = new javax.swing.JLabel();
        jp_OptionButton = new javax.swing.JPanel();
        jl_Option = new javax.swing.JLabel();
        jp_ExitButton = new javax.swing.JPanel();
        jl_Exit = new javax.swing.JLabel();
        jp_changeAcc = new javax.swing.JPanel();
        jl_changeAcc = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_Background.setBackground(new java.awt.Color(102, 102, 102));

        jp_MainMenu.setBackground(new java.awt.Color(0, 0, 0));

        jl_AccountName.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jl_AccountName.setForeground(new java.awt.Color(255, 255, 255));
        jl_AccountName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jl_AccountName.setText("welcome,yurtan");

        jp_PlayButton.setBackground(new java.awt.Color(0, 0, 0));
        jp_PlayButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jp_PlayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_PlayButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_ExitButtonMouseExited(evt);
            }
        });

        jl_Play.setBackground(new java.awt.Color(255, 255, 255));
        jl_Play.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_Play.setForeground(new java.awt.Color(255, 255, 255));
        jl_Play.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Play.setText("PLAY");

        javax.swing.GroupLayout jp_PlayButtonLayout = new javax.swing.GroupLayout(jp_PlayButton);
        jp_PlayButton.setLayout(jp_PlayButtonLayout);
        jp_PlayButtonLayout.setHorizontalGroup(
            jp_PlayButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jp_PlayButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jl_Play, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
        );
        jp_PlayButtonLayout.setVerticalGroup(
            jp_PlayButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
            .addGroup(jp_PlayButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_PlayButtonLayout.createSequentialGroup()
                    .addComponent(jl_Play)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jp_DeckButton.setBackground(new java.awt.Color(0, 0, 0));
        jp_DeckButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_ExitButtonMouseExited(evt);
            }
        });

        jl_Deck.setBackground(new java.awt.Color(255, 255, 255));
        jl_Deck.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_Deck.setForeground(new java.awt.Color(255, 255, 255));
        jl_Deck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Deck.setText("DECK");

        javax.swing.GroupLayout jp_DeckButtonLayout = new javax.swing.GroupLayout(jp_DeckButton);
        jp_DeckButton.setLayout(jp_DeckButtonLayout);
        jp_DeckButtonLayout.setHorizontalGroup(
            jp_DeckButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Deck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_DeckButtonLayout.setVerticalGroup(
            jp_DeckButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Deck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jp_HelpButton.setBackground(new java.awt.Color(0, 0, 0));
        jp_HelpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_ExitButtonMouseExited(evt);
            }
        });

        jl_Help.setBackground(new java.awt.Color(255, 255, 255));
        jl_Help.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_Help.setForeground(new java.awt.Color(255, 255, 255));
        jl_Help.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Help.setText("HELP");
        jl_Help.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jp_HelpButtonLayout = new javax.swing.GroupLayout(jp_HelpButton);
        jp_HelpButton.setLayout(jp_HelpButtonLayout);
        jp_HelpButtonLayout.setHorizontalGroup(
            jp_HelpButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_HelpButtonLayout.createSequentialGroup()
                .addComponent(jl_Help, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jp_HelpButtonLayout.setVerticalGroup(
            jp_HelpButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Help, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jp_OptionButton.setBackground(new java.awt.Color(0, 0, 0));
        jp_OptionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_ExitButtonMouseExited(evt);
            }
        });

        jl_Option.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_Option.setForeground(new java.awt.Color(255, 255, 255));
        jl_Option.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Option.setText("OPTION");

        javax.swing.GroupLayout jp_OptionButtonLayout = new javax.swing.GroupLayout(jp_OptionButton);
        jp_OptionButton.setLayout(jp_OptionButtonLayout);
        jp_OptionButtonLayout.setHorizontalGroup(
            jp_OptionButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Option, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_OptionButtonLayout.setVerticalGroup(
            jp_OptionButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_OptionButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jl_Option))
        );

        jp_ExitButton.setBackground(new java.awt.Color(0, 0, 0));
        jp_ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_ExitButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_ExitButtonMouseExited(evt);
            }
        });

        jl_Exit.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_Exit.setForeground(new java.awt.Color(255, 255, 255));
        jl_Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Exit.setText("EXIT");

        javax.swing.GroupLayout jp_ExitButtonLayout = new javax.swing.GroupLayout(jp_ExitButton);
        jp_ExitButton.setLayout(jp_ExitButtonLayout);
        jp_ExitButtonLayout.setHorizontalGroup(
            jp_ExitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_ExitButtonLayout.setVerticalGroup(
            jp_ExitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_ExitButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jl_Exit))
        );

        jp_changeAcc.setBackground(new java.awt.Color(255, 255, 255));
        jp_changeAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_changeAccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_changeAccMouseExited(evt);
            }
        });

        jl_changeAcc.setBackground(new java.awt.Color(0, 0, 0));
        jl_changeAcc.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_changeAcc.setForeground(new java.awt.Color(0, 0, 0));
        jl_changeAcc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_changeAcc.setText("Change Account");

        javax.swing.GroupLayout jp_changeAccLayout = new javax.swing.GroupLayout(jp_changeAcc);
        jp_changeAcc.setLayout(jp_changeAccLayout);
        jp_changeAccLayout.setHorizontalGroup(
            jp_changeAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_changeAccLayout.createSequentialGroup()
                .addComponent(jl_changeAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jp_changeAccLayout.setVerticalGroup(
            jp_changeAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_changeAcc, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jp_MainMenuLayout = new javax.swing.GroupLayout(jp_MainMenu);
        jp_MainMenu.setLayout(jp_MainMenuLayout);
        jp_MainMenuLayout.setHorizontalGroup(
            jp_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_MainMenuLayout.createSequentialGroup()
                .addGroup(jp_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jp_ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_PlayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_OptionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_DeckButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_HelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(500, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_MainMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jp_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_MainMenuLayout.createSequentialGroup()
                        .addComponent(jp_changeAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_MainMenuLayout.createSequentialGroup()
                        .addComponent(jl_AccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jp_MainMenuLayout.setVerticalGroup(
            jp_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_MainMenuLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jp_PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jp_DeckButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jp_OptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jp_HelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jp_ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jl_AccountName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_changeAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jp_BackgroundLayout = new javax.swing.GroupLayout(jp_Background);
        jp_Background.setLayout(jp_BackgroundLayout);
        jp_BackgroundLayout.setHorizontalGroup(
            jp_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_MainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_BackgroundLayout.setVerticalGroup(
            jp_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_MainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp_Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setColor(JPanel p, JLabel x){
        p.setBackground(Color.WHITE);
        x.setForeground(Color.BLACK);
    }
    public void resetColor(JPanel p, JLabel l){
        p.setBackground(Color.BLACK);
        l.setForeground(Color.WHITE);
    }

    private void jp_changeAccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_changeAccMouseEntered
        resetColor(jp_changeAcc, jl_changeAcc);
    }//GEN-LAST:event_jp_changeAccMouseEntered

    private void jp_changeAccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_changeAccMouseExited
        setColor(jp_changeAcc, jl_changeAcc);
    }//GEN-LAST:event_jp_changeAccMouseExited

    private void jp_PlayButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_PlayButtonMouseClicked
        
    }//GEN-LAST:event_jp_PlayButtonMouseClicked

    private void jp_MenuButtonEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_MenuButtonEntered
        // TODO add your handling code here:
        if(evt.getSource() instanceof JPanel jp)
        {
            ((JLabel)jp.getComponent(0)).setForeground(Color.BLACK);
            jp.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jp_MenuButtonEntered

    private void jp_ExitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_ExitButtonMouseExited
        // TODO add your handling code here:
        if(evt.getSource() instanceof JPanel jp)
        {
            ((JLabel)jp.getComponent(0)).setForeground(Color.WHITE);
            jp.setBackground(Color.BLACK);
        }
    }//GEN-LAST:event_jp_ExitButtonMouseExited

    private void jp_ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_ExitButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jp_ExitButtonMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Program program = new Program();
            program.fullScreen();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jl_AccountName;
    private javax.swing.JLabel jl_Deck;
    private javax.swing.JLabel jl_Exit;
    private javax.swing.JLabel jl_Help;
    private javax.swing.JLabel jl_Option;
    private javax.swing.JLabel jl_Play;
    private javax.swing.JLabel jl_changeAcc;
    private javax.swing.JPanel jp_Background;
    private javax.swing.JPanel jp_DeckButton;
    private javax.swing.JPanel jp_ExitButton;
    private javax.swing.JPanel jp_HelpButton;
    private javax.swing.JPanel jp_MainMenu;
    private javax.swing.JPanel jp_OptionButton;
    private javax.swing.JPanel jp_PlayButton;
    private javax.swing.JPanel jp_changeAcc;
    // End of variables declaration//GEN-END:variables
}
