package mgw.main;


import javax.swing.JFrame;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.*;
import mgw.gameplay.Skill;
import mgw.util.Screen;
import jaco.mp3.player.MP3Player;
import java.nio.file.Paths;
import javax.sound.sampled.FloatControl;
import javax.sound.sampled.Line;
import javax.sound.sampled.Mixer;
import mgw.util.FileTypeFilter;

public final class Program extends javax.swing.JFrame{
    
    MP3Player player = new MP3Player();
    File[] songFiles = {
        new File("src//BGM//MP3//mystical_piano.mp3"), //Main menu music 1
        new File("src//BGM//MP3//Main menu.mp3"), //Main menu music 2
        new File("src//BGM//MP3//Battle.mp3") //Battle music 1
    };
    
    ArrayList<Account> accounts = new ArrayList<>();
    Account activeAccount = null;
    SkillCard card[] = new SkillCard[Skill.list.length];
    Deck deck[] = new Deck[5];
    
    //String currentDirectionary = "home.user";
    //String currentPath;
    
    int screenWidth = (int)Screen.size().getWidth(); // the width of the screen
    int screenHeight = (int)Screen.size().getHeight(); // the height of the screen
    
    public Program() throws IOException, UnsupportedAudioFileException, LineUnavailableException {
        this.setUndecorated(true);
        initComponents();
        gameUI1.setProgram(this);
        
        accounts.add(new Account("Yurtan"));
        setActiveAccount(accounts.get(0));
        
        initCard();
        checkCard();
        
        initDeck();
        checkDeck();
         
        initBackGround();
        playMusic(songFiles[1]);
        
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jp_Background = new javax.swing.JPanel();
        jp_MainMenu = new javax.swing.JPanel();
        jl_AccountName = new javax.swing.JLabel();
        jp_PlayButton = new javax.swing.JPanel();
        jl_Play = new javax.swing.JLabel();
        jp_DeckButton = new javax.swing.JPanel();
        jl_Deck = new javax.swing.JLabel();
        jp_HelpButton = new javax.swing.JPanel();
        jl_Help = new javax.swing.JLabel();
        jp_OptionButton = new javax.swing.JPanel();
        jl_Option = new javax.swing.JLabel();
        jp_ExitButton = new javax.swing.JPanel();
        jl_Exit = new javax.swing.JLabel();
        jp_changeAcc = new javax.swing.JPanel();
        jl_changeAcc = new javax.swing.JLabel();
        jp_PlayMenu = new javax.swing.JPanel();
        gameUI1 = new mgw.main.GameUI();
        jp_DeckMenu = new javax.swing.JPanel();
        jp_BackDeck = new javax.swing.JPanel();
        jl_BackDeck = new javax.swing.JLabel();
        jp_ListOfCard = new javax.swing.JPanel();
        jp_SkillDesc = new javax.swing.JPanel();
        jp_DescriptionBody = new javax.swing.JPanel();
        jta_DescriptionBody = new javax.swing.JTextArea();
        jta_DescriptionBody_SP = new javax.swing.JTextArea();
        jl_DescriptionHeading = new javax.swing.JLabel();
        jp_ListOfDeck = new javax.swing.JPanel();
        jp_HelpMenu = new javax.swing.JPanel();
        jp_BackHelp = new javax.swing.JPanel();
        jl_BackHelp = new javax.swing.JLabel();
        jp_BodyHelp = new javax.swing.JPanel();
        jp_JudulDesk = new javax.swing.JPanel();
        jl_JudulDesk = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Help_desc = new javax.swing.JTextArea();
        jp_OptionMenu = new javax.swing.JPanel();
        jp_BackOption = new javax.swing.JPanel();
        jl_BackOption = new javax.swing.JLabel();
        jp_VolumeDown = new javax.swing.JPanel();
        jl_VolumeDown = new javax.swing.JLabel();
        jp_VolumeUp = new javax.swing.JPanel();
        jl_VolumeUp = new javax.swing.JLabel();
        jp_MinButton = new javax.swing.JPanel();
        jl_Min = new javax.swing.JLabel();
        jp_MaxButton = new javax.swing.JPanel();
        jl_Max = new javax.swing.JLabel();
        jp_Volume = new javax.swing.JPanel();
        jl_Volume = new javax.swing.JLabel();
        jp_ExitConfirmation = new javax.swing.JPanel();
        jl_ExitConfirmation = new javax.swing.JLabel();
        jp_ExitOKButton = new javax.swing.JPanel();
        jl_ExitOk = new javax.swing.JLabel();
        jp_ExitCancelButton = new javax.swing.JPanel();
        jl_ExitCancel = new javax.swing.JLabel();
        jp_ChangeAccount = new javax.swing.JPanel();
        lb_ChangeAccount = new javax.swing.JLabel();
        jcb_ChooseAccount = new javax.swing.JComboBox<>();
        jp_ChangeAccountSelectButton = new javax.swing.JPanel();
        jl_ChangeAccountSelectButton = new javax.swing.JLabel();
        jp_ChangeAccountCreateButton = new javax.swing.JPanel();
        jl_ChangeAccountCreateButton = new javax.swing.JLabel();
        jp_CreateAccount = new javax.swing.JPanel();
        lb_CreateAccount = new javax.swing.JLabel();
        jtf_AccountName = new javax.swing.JTextField();
        jp_CreateAccountButton = new javax.swing.JPanel();
        jl_CreateAccountButton = new javax.swing.JLabel();
        jl_CreateAccountFailed = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_Background.setBackground(new java.awt.Color(102, 102, 102));
        jp_Background.setLayout(new java.awt.CardLayout());

        jp_MainMenu.setBackground(new java.awt.Color(0, 0, 0));

        jl_AccountName.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jl_AccountName.setForeground(new java.awt.Color(255, 255, 255));
        jl_AccountName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jl_AccountName.setText("welcome,yurtan");

        jp_PlayButton.setBackground(new java.awt.Color(0, 0, 0));
        jp_PlayButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jp_PlayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_PlayButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonWhite(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_MenuButtonBlack(evt);
            }
        });

        jl_Play.setBackground(new java.awt.Color(255, 255, 255));
        jl_Play.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_Play.setForeground(new java.awt.Color(255, 255, 255));
        jl_Play.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Play.setText("PLAY");

        javax.swing.GroupLayout jp_PlayButtonLayout = new javax.swing.GroupLayout(jp_PlayButton);
        jp_PlayButton.setLayout(jp_PlayButtonLayout);
        jp_PlayButtonLayout.setHorizontalGroup(
            jp_PlayButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jp_PlayButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jl_Play, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
        );
        jp_PlayButtonLayout.setVerticalGroup(
            jp_PlayButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
            .addGroup(jp_PlayButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_PlayButtonLayout.createSequentialGroup()
                    .addComponent(jl_Play)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jp_DeckButton.setBackground(new java.awt.Color(0, 0, 0));
        jp_DeckButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_DeckButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonWhite(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_MenuButtonBlack(evt);
            }
        });

        jl_Deck.setBackground(new java.awt.Color(255, 255, 255));
        jl_Deck.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_Deck.setForeground(new java.awt.Color(255, 255, 255));
        jl_Deck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Deck.setText("DECK");

        javax.swing.GroupLayout jp_DeckButtonLayout = new javax.swing.GroupLayout(jp_DeckButton);
        jp_DeckButton.setLayout(jp_DeckButtonLayout);
        jp_DeckButtonLayout.setHorizontalGroup(
            jp_DeckButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Deck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_DeckButtonLayout.setVerticalGroup(
            jp_DeckButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Deck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jp_HelpButton.setBackground(new java.awt.Color(0, 0, 0));
        jp_HelpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_HelpButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonWhite(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_MenuButtonBlack(evt);
            }
        });

        jl_Help.setBackground(new java.awt.Color(255, 255, 255));
        jl_Help.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_Help.setForeground(new java.awt.Color(255, 255, 255));
        jl_Help.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Help.setText("HELP");
        jl_Help.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jp_HelpButtonLayout = new javax.swing.GroupLayout(jp_HelpButton);
        jp_HelpButton.setLayout(jp_HelpButtonLayout);
        jp_HelpButtonLayout.setHorizontalGroup(
            jp_HelpButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_HelpButtonLayout.createSequentialGroup()
                .addComponent(jl_Help, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jp_HelpButtonLayout.setVerticalGroup(
            jp_HelpButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Help, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jp_OptionButton.setBackground(new java.awt.Color(0, 0, 0));
        jp_OptionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_OptionButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonWhite(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_MenuButtonBlack(evt);
            }
        });

        jl_Option.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_Option.setForeground(new java.awt.Color(255, 255, 255));
        jl_Option.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Option.setText("OPTION");

        javax.swing.GroupLayout jp_OptionButtonLayout = new javax.swing.GroupLayout(jp_OptionButton);
        jp_OptionButton.setLayout(jp_OptionButtonLayout);
        jp_OptionButtonLayout.setHorizontalGroup(
            jp_OptionButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Option, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_OptionButtonLayout.setVerticalGroup(
            jp_OptionButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_OptionButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jl_Option))
        );

        jp_ExitButton.setBackground(new java.awt.Color(0, 0, 0));
        jp_ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_ExitButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonWhite(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_MenuButtonBlack(evt);
            }
        });

        jl_Exit.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_Exit.setForeground(new java.awt.Color(255, 255, 255));
        jl_Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Exit.setText("EXIT");

        javax.swing.GroupLayout jp_ExitButtonLayout = new javax.swing.GroupLayout(jp_ExitButton);
        jp_ExitButton.setLayout(jp_ExitButtonLayout);
        jp_ExitButtonLayout.setHorizontalGroup(
            jp_ExitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_ExitButtonLayout.setVerticalGroup(
            jp_ExitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_ExitButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jl_Exit))
        );

        jp_changeAcc.setBackground(new java.awt.Color(255, 255, 255));
        jp_changeAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_changeAccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonBlack(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_MenuButtonWhite(evt);
            }
        });

        jl_changeAcc.setBackground(new java.awt.Color(0, 0, 0));
        jl_changeAcc.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_changeAcc.setForeground(new java.awt.Color(0, 0, 0));
        jl_changeAcc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_changeAcc.setText("Change Account");

        javax.swing.GroupLayout jp_changeAccLayout = new javax.swing.GroupLayout(jp_changeAcc);
        jp_changeAcc.setLayout(jp_changeAccLayout);
        jp_changeAccLayout.setHorizontalGroup(
            jp_changeAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_changeAccLayout.createSequentialGroup()
                .addComponent(jl_changeAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 60, Short.MAX_VALUE))
        );
        jp_changeAccLayout.setVerticalGroup(
            jp_changeAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_changeAcc, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jp_MainMenuLayout = new javax.swing.GroupLayout(jp_MainMenu);
        jp_MainMenu.setLayout(jp_MainMenuLayout);
        jp_MainMenuLayout.setHorizontalGroup(
            jp_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_MainMenuLayout.createSequentialGroup()
                .addGroup(jp_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_MainMenuLayout.createSequentialGroup()
                        .addGroup(jp_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jp_ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp_PlayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp_OptionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp_DeckButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp_HelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 1205, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_MainMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jl_AccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_MainMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jp_changeAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jp_MainMenuLayout.setVerticalGroup(
            jp_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_MainMenuLayout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(jp_PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jp_DeckButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jp_OptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jp_HelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jp_ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jl_AccountName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_changeAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jp_Background.add(jp_MainMenu, "card8");

        javax.swing.GroupLayout jp_PlayMenuLayout = new javax.swing.GroupLayout(jp_PlayMenu);
        jp_PlayMenu.setLayout(jp_PlayMenuLayout);
        jp_PlayMenuLayout.setHorizontalGroup(
            jp_PlayMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameUI1, javax.swing.GroupLayout.DEFAULT_SIZE, 1530, Short.MAX_VALUE)
        );
        jp_PlayMenuLayout.setVerticalGroup(
            jp_PlayMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameUI1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );

        jp_Background.add(jp_PlayMenu, "card3");

        jp_BackDeck.setBackground(new java.awt.Color(0, 0, 0));
        jp_BackDeck.setPreferredSize(new java.awt.Dimension(100, 40));
        jp_BackDeck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_BackDeckMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonWhite(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_MenuButtonBlack(evt);
            }
        });

        jl_BackDeck.setBackground(new java.awt.Color(255, 255, 255));
        jl_BackDeck.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_BackDeck.setForeground(new java.awt.Color(255, 255, 255));
        jl_BackDeck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_BackDeck.setText("back");

        javax.swing.GroupLayout jp_BackDeckLayout = new javax.swing.GroupLayout(jp_BackDeck);
        jp_BackDeck.setLayout(jp_BackDeckLayout);
        jp_BackDeckLayout.setHorizontalGroup(
            jp_BackDeckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_BackDeck, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jp_BackDeckLayout.setVerticalGroup(
            jp_BackDeckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_BackDeck, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jp_ListOfCardLayout = new javax.swing.GroupLayout(jp_ListOfCard);
        jp_ListOfCard.setLayout(jp_ListOfCardLayout);
        jp_ListOfCardLayout.setHorizontalGroup(
            jp_ListOfCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jp_ListOfCardLayout.setVerticalGroup(
            jp_ListOfCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        jta_DescriptionBody.setEditable(false);
        jta_DescriptionBody.setColumns(20);
        jta_DescriptionBody.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jta_DescriptionBody.setLineWrap(true);
        jta_DescriptionBody.setRows(5);
        jta_DescriptionBody.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jta_DescriptionBody_SP.setEditable(false);
        jta_DescriptionBody_SP.setColumns(20);
        jta_DescriptionBody_SP.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jta_DescriptionBody_SP.setLineWrap(true);
        jta_DescriptionBody_SP.setRows(5);
        jta_DescriptionBody_SP.setAutoscrolls(false);

        jl_DescriptionHeading.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jl_DescriptionHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_DescriptionHeading.setText("Skill Name");

        javax.swing.GroupLayout jp_DescriptionBodyLayout = new javax.swing.GroupLayout(jp_DescriptionBody);
        jp_DescriptionBody.setLayout(jp_DescriptionBodyLayout);
        jp_DescriptionBodyLayout.setHorizontalGroup(
            jp_DescriptionBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jta_DescriptionBody_SP, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jta_DescriptionBody, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jl_DescriptionHeading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_DescriptionBodyLayout.setVerticalGroup(
            jp_DescriptionBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_DescriptionBodyLayout.createSequentialGroup()
                .addComponent(jl_DescriptionHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(jta_DescriptionBody, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(jta_DescriptionBody_SP, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jp_SkillDescLayout = new javax.swing.GroupLayout(jp_SkillDesc);
        jp_SkillDesc.setLayout(jp_SkillDescLayout);
        jp_SkillDescLayout.setHorizontalGroup(
            jp_SkillDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_SkillDescLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jp_DescriptionBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_SkillDescLayout.setVerticalGroup(
            jp_SkillDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_DescriptionBody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jp_ListOfDeck.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jp_ListOfDeckLayout = new javax.swing.GroupLayout(jp_ListOfDeck);
        jp_ListOfDeck.setLayout(jp_ListOfDeckLayout);
        jp_ListOfDeckLayout.setHorizontalGroup(
            jp_ListOfDeckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );
        jp_ListOfDeckLayout.setVerticalGroup(
            jp_ListOfDeckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jp_DeckMenuLayout = new javax.swing.GroupLayout(jp_DeckMenu);
        jp_DeckMenu.setLayout(jp_DeckMenuLayout);
        jp_DeckMenuLayout.setHorizontalGroup(
            jp_DeckMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_DeckMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jp_ListOfDeck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jp_DeckMenuLayout.createSequentialGroup()
                .addGroup(jp_DeckMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_DeckMenuLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jp_ListOfCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_DeckMenuLayout.createSequentialGroup()
                        .addComponent(jp_BackDeck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_SkillDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_DeckMenuLayout.setVerticalGroup(
            jp_DeckMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_DeckMenuLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jp_BackDeck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jp_DeckMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_ListOfCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_SkillDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jp_ListOfDeck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jp_Background.add(jp_DeckMenu, "card3");

        jp_HelpMenu.setPreferredSize(new java.awt.Dimension(1200, 800));

        jp_BackHelp.setBackground(new java.awt.Color(0, 0, 0));
        jp_BackHelp.setPreferredSize(new java.awt.Dimension(100, 40));
        jp_BackHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_BackHelpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonWhite(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_MenuButtonBlack(evt);
            }
        });

        jl_BackHelp.setBackground(new java.awt.Color(255, 255, 255));
        jl_BackHelp.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_BackHelp.setForeground(new java.awt.Color(255, 255, 255));
        jl_BackHelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_BackHelp.setText("back");

        javax.swing.GroupLayout jp_BackHelpLayout = new javax.swing.GroupLayout(jp_BackHelp);
        jp_BackHelp.setLayout(jp_BackHelpLayout);
        jp_BackHelpLayout.setHorizontalGroup(
            jp_BackHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_BackHelp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jp_BackHelpLayout.setVerticalGroup(
            jp_BackHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_BackHelp, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jp_BodyHelp.setBackground(new java.awt.Color(0, 0, 0));
        jp_BodyHelp.setPreferredSize(new java.awt.Dimension(1200, 650));

        jp_JudulDesk.setBackground(new java.awt.Color(255, 255, 255));

        jl_JudulDesk.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jl_JudulDesk.setForeground(new java.awt.Color(0, 0, 0));
        jl_JudulDesk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jl_JudulDesk.setText("How To Play");

        javax.swing.GroupLayout jp_JudulDeskLayout = new javax.swing.GroupLayout(jp_JudulDesk);
        jp_JudulDesk.setLayout(jp_JudulDeskLayout);
        jp_JudulDeskLayout.setHorizontalGroup(
            jp_JudulDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_JudulDesk, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jp_JudulDeskLayout.setVerticalGroup(
            jp_JudulDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_JudulDesk, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        Help_desc.setEditable(false);
        Help_desc.setBackground(new java.awt.Color(0, 0, 0));
        Help_desc.setColumns(20);
        Help_desc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Help_desc.setForeground(new java.awt.Color(255, 255, 255));
        Help_desc.setLineWrap(true);
        Help_desc.setRows(5);
        Help_desc.setText("In the Main Menu, you can add a user or change user by clicking the \"change user\" button.\n\nAfter adding the user, you need to set up your deck in order to play the game.\nIn the Main Menu, click on the \"DECK\" button.\nIn the DECK menu, you can arrange several skills to the deck (don't forget to read the skill description).\n\nAfter you finish your deck set up, click on the \"PLAY\" button.\nOn the game board, there are always two identical images. \nStart the game by flipping a card. \nThen try to find another card that has the same image as the first. \nIf you can't find a pair, the flipped cards will be flipped back with the face down.\nYour turn will be ended if you cant find a pair, or if you flipped all the cards on the board\n\nEvery time you find a pair, you will get 2 Skill Points (SP).\nYou can use the skill points you get to activate the skills in your deck to defeat your opponent.");
        jScrollPane1.setViewportView(Help_desc);

        javax.swing.GroupLayout jp_BodyHelpLayout = new javax.swing.GroupLayout(jp_BodyHelp);
        jp_BodyHelp.setLayout(jp_BodyHelpLayout);
        jp_BodyHelpLayout.setHorizontalGroup(
            jp_BodyHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_BodyHelpLayout.createSequentialGroup()
                .addComponent(jp_JudulDesk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1060, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jp_BodyHelpLayout.setVerticalGroup(
            jp_BodyHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_BodyHelpLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jp_JudulDesk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp_HelpMenuLayout = new javax.swing.GroupLayout(jp_HelpMenu);
        jp_HelpMenu.setLayout(jp_HelpMenuLayout);
        jp_HelpMenuLayout.setHorizontalGroup(
            jp_HelpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_HelpMenuLayout.createSequentialGroup()
                .addComponent(jp_BackHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jp_HelpMenuLayout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addComponent(jp_BodyHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jp_HelpMenuLayout.setVerticalGroup(
            jp_HelpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_HelpMenuLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jp_BackHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jp_BodyHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp_Background.add(jp_HelpMenu, "card3");

        jp_BackOption.setBackground(new java.awt.Color(0, 0, 0));
        jp_BackOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_BackOptionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonWhite(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_MenuButtonBlack(evt);
            }
        });

        jl_BackOption.setBackground(new java.awt.Color(255, 255, 255));
        jl_BackOption.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_BackOption.setForeground(new java.awt.Color(255, 255, 255));
        jl_BackOption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_BackOption.setText("back");

        javax.swing.GroupLayout jp_BackOptionLayout = new javax.swing.GroupLayout(jp_BackOption);
        jp_BackOption.setLayout(jp_BackOptionLayout);
        jp_BackOptionLayout.setHorizontalGroup(
            jp_BackOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_BackOption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jp_BackOptionLayout.setVerticalGroup(
            jp_BackOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_BackOption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jp_VolumeDown.setBackground(new java.awt.Color(0, 0, 0));
        jp_VolumeDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_VolumeDownMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonWhite(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_MenuButtonBlack(evt);
            }
        });

        jl_VolumeDown.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jl_VolumeDown.setForeground(new java.awt.Color(255, 255, 255));
        jl_VolumeDown.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_VolumeDown.setText("-");

        javax.swing.GroupLayout jp_VolumeDownLayout = new javax.swing.GroupLayout(jp_VolumeDown);
        jp_VolumeDown.setLayout(jp_VolumeDownLayout);
        jp_VolumeDownLayout.setHorizontalGroup(
            jp_VolumeDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_VolumeDown, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );
        jp_VolumeDownLayout.setVerticalGroup(
            jp_VolumeDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_VolumeDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jp_VolumeUp.setBackground(new java.awt.Color(0, 0, 0));
        jp_VolumeUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_VolumeUpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonWhite(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_MenuButtonBlack(evt);
            }
        });

        jl_VolumeUp.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jl_VolumeUp.setForeground(new java.awt.Color(255, 255, 255));
        jl_VolumeUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_VolumeUp.setText("+");

        javax.swing.GroupLayout jp_VolumeUpLayout = new javax.swing.GroupLayout(jp_VolumeUp);
        jp_VolumeUp.setLayout(jp_VolumeUpLayout);
        jp_VolumeUpLayout.setHorizontalGroup(
            jp_VolumeUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_VolumeUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );
        jp_VolumeUpLayout.setVerticalGroup(
            jp_VolumeUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_VolumeUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jp_MinButton.setBackground(new java.awt.Color(0, 0, 0));
        jp_MinButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_MinButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonWhite(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_MenuButtonBlack(evt);
            }
        });

        jl_Min.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_Min.setForeground(new java.awt.Color(255, 255, 255));
        jl_Min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Min.setText("Min");

        javax.swing.GroupLayout jp_MinButtonLayout = new javax.swing.GroupLayout(jp_MinButton);
        jp_MinButton.setLayout(jp_MinButtonLayout);
        jp_MinButtonLayout.setHorizontalGroup(
            jp_MinButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Min, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        jp_MinButtonLayout.setVerticalGroup(
            jp_MinButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Min, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jp_MaxButton.setBackground(new java.awt.Color(0, 0, 0));
        jp_MaxButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_MaxButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonWhite(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_MenuButtonBlack(evt);
            }
        });

        jl_Max.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_Max.setForeground(new java.awt.Color(255, 255, 255));
        jl_Max.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Max.setText("Max");

        javax.swing.GroupLayout jp_MaxButtonLayout = new javax.swing.GroupLayout(jp_MaxButton);
        jp_MaxButton.setLayout(jp_MaxButtonLayout);
        jp_MaxButtonLayout.setHorizontalGroup(
            jp_MaxButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Max, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        jp_MaxButtonLayout.setVerticalGroup(
            jp_MaxButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Max, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jp_Volume.setBackground(new java.awt.Color(0, 0, 0));

        jl_Volume.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jl_Volume.setForeground(new java.awt.Color(255, 255, 255));
        jl_Volume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Volume.setText("Volume");

        javax.swing.GroupLayout jp_VolumeLayout = new javax.swing.GroupLayout(jp_Volume);
        jp_Volume.setLayout(jp_VolumeLayout);
        jp_VolumeLayout.setHorizontalGroup(
            jp_VolumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Volume, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jp_VolumeLayout.setVerticalGroup(
            jp_VolumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Volume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jp_OptionMenuLayout = new javax.swing.GroupLayout(jp_OptionMenu);
        jp_OptionMenu.setLayout(jp_OptionMenuLayout);
        jp_OptionMenuLayout.setHorizontalGroup(
            jp_OptionMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_OptionMenuLayout.createSequentialGroup()
                .addComponent(jp_BackOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jp_OptionMenuLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jp_MinButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jp_VolumeDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jp_Volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jp_VolumeUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jp_MaxButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1079, Short.MAX_VALUE))
        );
        jp_OptionMenuLayout.setVerticalGroup(
            jp_OptionMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_OptionMenuLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jp_BackOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jp_OptionMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_VolumeUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp_MaxButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_OptionMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jp_VolumeDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jp_Volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jp_MinButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(681, Short.MAX_VALUE))
        );

        jp_Background.add(jp_OptionMenu, "card6");

        jp_ExitConfirmation.setBackground(new java.awt.Color(0, 0, 0));

        jl_ExitConfirmation.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jl_ExitConfirmation.setForeground(new java.awt.Color(255, 255, 255));
        jl_ExitConfirmation.setText("Are you sure you want to quit?");

        jp_ExitOKButton.setBackground(new java.awt.Color(255, 255, 255));
        jp_ExitOKButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_ExitOKButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_ExitOKButtonPoppupButtonEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_ExitOKButtonPoppupButtonExited(evt);
            }
        });

        jl_ExitOk.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jl_ExitOk.setForeground(new java.awt.Color(0, 0, 0));
        jl_ExitOk.setText("Exit");

        javax.swing.GroupLayout jp_ExitOKButtonLayout = new javax.swing.GroupLayout(jp_ExitOKButton);
        jp_ExitOKButton.setLayout(jp_ExitOKButtonLayout);
        jp_ExitOKButtonLayout.setHorizontalGroup(
            jp_ExitOKButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ExitOKButtonLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jl_ExitOk)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jp_ExitOKButtonLayout.setVerticalGroup(
            jp_ExitOKButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ExitOKButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_ExitOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp_ExitCancelButton.setBackground(new java.awt.Color(255, 255, 255));
        jp_ExitCancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_ExitCancelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_ExitCancelButtonPoppupButtonEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_ExitCancelButtonPoppupButtonExited(evt);
            }
        });

        jl_ExitCancel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jl_ExitCancel.setForeground(new java.awt.Color(0, 0, 0));
        jl_ExitCancel.setText("Cancel");

        javax.swing.GroupLayout jp_ExitCancelButtonLayout = new javax.swing.GroupLayout(jp_ExitCancelButton);
        jp_ExitCancelButton.setLayout(jp_ExitCancelButtonLayout);
        jp_ExitCancelButtonLayout.setHorizontalGroup(
            jp_ExitCancelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ExitCancelButtonLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jl_ExitCancel)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jp_ExitCancelButtonLayout.setVerticalGroup(
            jp_ExitCancelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ExitCancelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_ExitCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp_ExitConfirmationLayout = new javax.swing.GroupLayout(jp_ExitConfirmation);
        jp_ExitConfirmation.setLayout(jp_ExitConfirmationLayout);
        jp_ExitConfirmationLayout.setHorizontalGroup(
            jp_ExitConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ExitConfirmationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_ExitConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_ExitConfirmationLayout.createSequentialGroup()
                        .addComponent(jp_ExitOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jp_ExitCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jl_ExitConfirmation))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_ExitConfirmationLayout.setVerticalGroup(
            jp_ExitConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ExitConfirmationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl_ExitConfirmation)
                .addGap(54, 54, 54)
                .addGroup(jp_ExitConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_ExitOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp_ExitCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp_Background.add(jp_ExitConfirmation, "card7");

        jp_ChangeAccount.setBackground(new java.awt.Color(0, 0, 0));

        lb_ChangeAccount.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lb_ChangeAccount.setForeground(new java.awt.Color(255, 255, 255));
        lb_ChangeAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_ChangeAccount.setText("Change Account");

        jcb_ChooseAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jp_ChangeAccountSelectButton.setBackground(new java.awt.Color(255, 255, 255));
        jp_ChangeAccountSelectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_ChangeAccountSelectButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonBlack(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_MenuButtonWhite(evt);
            }
        });

        jl_ChangeAccountSelectButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jl_ChangeAccountSelectButton.setForeground(new java.awt.Color(0, 0, 0));
        jl_ChangeAccountSelectButton.setText("Select");

        javax.swing.GroupLayout jp_ChangeAccountSelectButtonLayout = new javax.swing.GroupLayout(jp_ChangeAccountSelectButton);
        jp_ChangeAccountSelectButton.setLayout(jp_ChangeAccountSelectButtonLayout);
        jp_ChangeAccountSelectButtonLayout.setHorizontalGroup(
            jp_ChangeAccountSelectButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ChangeAccountSelectButtonLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jl_ChangeAccountSelectButton)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jp_ChangeAccountSelectButtonLayout.setVerticalGroup(
            jp_ChangeAccountSelectButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ChangeAccountSelectButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_ChangeAccountSelectButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp_ChangeAccountCreateButton.setBackground(new java.awt.Color(255, 255, 255));
        jp_ChangeAccountCreateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_ChangeAccountCreateButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonBlack(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_MenuButtonWhite(evt);
            }
        });

        jl_ChangeAccountCreateButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jl_ChangeAccountCreateButton.setForeground(new java.awt.Color(0, 0, 0));
        jl_ChangeAccountCreateButton.setText("Create New");

        javax.swing.GroupLayout jp_ChangeAccountCreateButtonLayout = new javax.swing.GroupLayout(jp_ChangeAccountCreateButton);
        jp_ChangeAccountCreateButton.setLayout(jp_ChangeAccountCreateButtonLayout);
        jp_ChangeAccountCreateButtonLayout.setHorizontalGroup(
            jp_ChangeAccountCreateButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ChangeAccountCreateButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl_ChangeAccountCreateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_ChangeAccountCreateButtonLayout.setVerticalGroup(
            jp_ChangeAccountCreateButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ChangeAccountCreateButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_ChangeAccountCreateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp_ChangeAccountLayout = new javax.swing.GroupLayout(jp_ChangeAccount);
        jp_ChangeAccount.setLayout(jp_ChangeAccountLayout);
        jp_ChangeAccountLayout.setHorizontalGroup(
            jp_ChangeAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ChangeAccountLayout.createSequentialGroup()
                .addContainerGap(416, Short.MAX_VALUE)
                .addGroup(jp_ChangeAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_ChangeAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_ChangeAccountLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jp_ChangeAccountSelectButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jp_ChangeAccountCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)))
                .addContainerGap(418, Short.MAX_VALUE))
            .addGroup(jp_ChangeAccountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcb_ChooseAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_ChangeAccountLayout.setVerticalGroup(
            jp_ChangeAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ChangeAccountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_ChangeAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcb_ChooseAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jp_ChangeAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_ChangeAccountSelectButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp_ChangeAccountCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp_Background.add(jp_ChangeAccount, "card8");

        jp_CreateAccount.setBackground(new java.awt.Color(0, 0, 0));

        lb_CreateAccount.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lb_CreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        lb_CreateAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_CreateAccount.setText("Create Account");

        jtf_AccountName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jp_CreateAccountButton.setBackground(new java.awt.Color(255, 255, 255));
        jp_CreateAccountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_CreateAccountButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonBlack(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_MenuButtonWhite(evt);
            }
        });

        jl_CreateAccountButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jl_CreateAccountButton.setForeground(new java.awt.Color(0, 0, 0));
        jl_CreateAccountButton.setText("Create");

        javax.swing.GroupLayout jp_CreateAccountButtonLayout = new javax.swing.GroupLayout(jp_CreateAccountButton);
        jp_CreateAccountButton.setLayout(jp_CreateAccountButtonLayout);
        jp_CreateAccountButtonLayout.setHorizontalGroup(
            jp_CreateAccountButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_CreateAccountButtonLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jl_CreateAccountButton)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jp_CreateAccountButtonLayout.setVerticalGroup(
            jp_CreateAccountButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_CreateAccountButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_CreateAccountButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jl_CreateAccountFailed.setForeground(new java.awt.Color(255, 0, 0));
        jl_CreateAccountFailed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_CreateAccountFailed.setText(" ");

        javax.swing.GroupLayout jp_CreateAccountLayout = new javax.swing.GroupLayout(jp_CreateAccount);
        jp_CreateAccount.setLayout(jp_CreateAccountLayout);
        jp_CreateAccountLayout.setHorizontalGroup(
            jp_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_CreateAccountLayout.createSequentialGroup()
                .addContainerGap(281, Short.MAX_VALUE)
                .addGroup(jp_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_AccountName)
                    .addComponent(lb_CreateAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jl_CreateAccountFailed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(282, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_CreateAccountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jp_CreateAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_CreateAccountLayout.setVerticalGroup(
            jp_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_CreateAccountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jtf_AccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jl_CreateAccountFailed)
                .addGap(12, 12, 12)
                .addComponent(jp_CreateAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp_Background.add(jp_CreateAccount, "card9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp_Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void playMusic(File path) throws UnsupportedAudioFileException, IOException, LineUnavailableException{
        
        //openMusic();
        player.addToPlayList(path);
        //currentPath = Paths.get(".").toAbsolutePath().normalize().toString();
        player.skipForward();
        player.play();
        player.setRepeat(true);
        /*
        File file = new File("src\\BGM\\main menu.wav");
        AudioInputStream audioStream =  AudioSystem.getAudioInputStream(file);
        Clip clip = AudioSystem.getClip();
        clip.open(audioStream);
        clip.loop(-1);
        clip.start();*/
    }
    
    public void toMainMenu()
    {
        changeTo(jp_MainMenu);
    }
    
//    private void openMusic(){
//        JFileChooser opFileChooser = new JFileChooser(currentDirectionary);
//        opFileChooser.setFileFilter(new FileTypeFilter(".mp3", "Open MP3 Files Only!"));
//        int result = opFileChooser.showOpenDialog(null);
//        if(result == JFileChooser.APPROVE_OPTION){
//            songFiles = opFileChooser.getSelectedFile();
//            player.addToPlayList(songFiles);
//            player.skipForward();
//            currentDirectionary = songFiles.getAbsolutePath();
//        }
//        
//    }
    
//    private MP3Player mp3Player(){
//        return new MP3Player();
//    }
    
    private void volumeDown(Double value){
        Mixer.Info[] mixers = AudioSystem.getMixerInfo();
        for(Mixer.Info i : mixers){
            Mixer mixer = AudioSystem.getMixer(i);
            Line.Info[] lineInfo = mixer.getTargetLineInfo();
            for(Line.Info j : lineInfo){
                Line line = null;
                boolean opened = true;
                try
                {
                    line = mixer.getLine(j);
                    opened = line.isOpen() || line instanceof Clip;
                    if(!opened){
                        line.open();
                    }
                    FloatControl volControl = (FloatControl) line.getControl(FloatControl.Type.VOLUME);
                    float currentVolume = volControl.getValue();
                    Double volumeToCut = value;
                    float changedCalc = (float)((float) currentVolume - (double) volumeToCut);
                    volControl.setValue(changedCalc);
                } 
                catch (LineUnavailableException | IllegalArgumentException e) {}
                finally
                {
                    if(line != null && !opened){
                        line.close();
                    }
                }
            }
        }
    }
    private void volumeUp(Double value){
        Mixer.Info[] mixers = AudioSystem.getMixerInfo();
        for(Mixer.Info i : mixers){
            Mixer mixer = AudioSystem.getMixer(i);
            Line.Info[] lineInfo = mixer.getTargetLineInfo();
            for(Line.Info j : lineInfo){
                Line line = null;
                boolean opened = true;
                try {
                    line = mixer.getLine(j);
                    opened = line.isOpen() || line instanceof Clip;
                    if(!opened){
                        line.open();
                    }
                    FloatControl volControl = (FloatControl) line.getControl(FloatControl.Type.VOLUME);
                    float currentVolume = volControl.getValue();
                    Double volumeToCut = value;
                    float changedCalc = (float)((float) currentVolume + (double) volumeToCut);
                    volControl.setValue(changedCalc);
                } catch (LineUnavailableException e) {
                } catch (IllegalArgumentException illException){
                } finally{
                    if(line != null && !opened){
                        line.close();
                    }
                }
            }
        }
    }
    private void volumeControl(Double value){
        Mixer.Info[] mixers = AudioSystem.getMixerInfo();
        for(Mixer.Info i : mixers){
            Mixer mixer = AudioSystem.getMixer(i);
            Line.Info[] lineInfo = mixer.getTargetLineInfo();
            for(Line.Info j : lineInfo){
                Line line = null;
                boolean opened = true;
                try {
                    line = mixer.getLine(j);
                    opened = line.isOpen() || line instanceof Clip;
                    if(!opened){
                        line.open();
                    }
                    FloatControl volControl = (FloatControl) line.getControl(FloatControl.Type.VOLUME);
                    float currentVolume = volControl.getValue();
                    Double volumeToCut = value;
                    float changedCalc = (float)((double) volumeToCut);
                    volControl.setValue(changedCalc);
                } catch (LineUnavailableException e) {
                } catch (IllegalArgumentException illException){
                } finally{
                    if(line != null && !opened){
                        line.close();
                    }
                }
            }
        }
    }
    
    public void initBackGround() throws IOException{
        Image vithun = ImageIO.read(new File("src\\mgw\\main\\background\\2000 x 1140.png")).getScaledInstance(screenWidth, screenHeight, Image.SCALE_SMOOTH);
        Image arsa = ImageIO.read(new File("src\\mgw\\main\\background\\2000 x 1333.png")).getScaledInstance(screenWidth, screenHeight, Image.SCALE_SMOOTH);
        Image yurtan = ImageIO.read(new File("src\\mgw\\main\\background\\3000 x 1500.jpg")).getScaledInstance(screenWidth, screenHeight, Image.SCALE_SMOOTH);
        Image simon = ImageIO.read(new File("src\\mgw\\main\\background\\3000 x 1000.jpg")).getScaledInstance(screenWidth, screenHeight, Image.SCALE_SMOOTH);
        Image help = ImageIO.read(new File("src\\mgw\\main\\background\\help.png")).getScaledInstance(screenWidth, screenHeight, Image.SCALE_SMOOTH);
        jp_MainMenu.add(new LatarBelakang(vithun, screenWidth, screenHeight));
        jp_PlayMenu.add(new LatarBelakang(simon, screenWidth, screenHeight));
        jp_OptionMenu.add(new LatarBelakang(yurtan, screenWidth, screenHeight));
        jp_HelpMenu.add(new LatarBelakang(help, screenWidth, screenHeight));
        jp_DeckMenu.add(new LatarBelakang(arsa, screenWidth, screenHeight));
    }
  
    public final void fullScreen()
    {
        this.setResizable(false);
        Screen.screenGD.setFullScreenWindow(this);
    }
    
    public void setActiveAccount(Account a){
        activeAccount = a;
        jl_AccountName.setText("Haii " + a.toString());
    }
   
    public void checkCard(){
        for (SkillCard card1 : card) {
            card1.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    cardClicked(evt);
                }
                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    cardEntered(evt);
                }
                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    cardExited(evt);
                }
            });
        }
    }
    public void checkDeck(){
        for (Deck deck1 : deck) {
            deck1.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    deckClicked(evt);
                }
                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    deckEntered(evt);
                }
                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    deckExited(evt);
                }
            });
        }
    }
    
    public void deckClicked(java.awt.event.MouseEvent evt){
        if(evt.getSource() instanceof Deck d){
            if(!d.empty){
                d.deckRemove(card);
            }
        }
    }
    public void deckEntered(java.awt.event.MouseEvent evt){
        if(evt.getSource() instanceof Deck d){
            
        }
    }
    public void deckExited(java.awt.event.MouseEvent evt){
        if(evt.getSource() instanceof Deck d){
            
        }
    }
    
    private void cardClicked(java.awt.event.MouseEvent evt){
        if(evt.getSource() instanceof SkillCard c){
            if(c.clicked)
                return;
            if(Deck.counter > 5)
                return;
            for(Deck i : deck)
                if(i.skill == null){
                    i.deckCopy(c);
                    return;
                }
        }
    }
    
    private void cardEntered(java.awt.event.MouseEvent evt){
        if(evt.getSource() instanceof SkillCard c)
        {
            setDescription(c.skill);
        }
        
    }
    private void cardExited(java.awt.event.MouseEvent evt){
        if(evt.getSource() instanceof SkillCard c)
        {
            setDescriptionDefault();
        }
    }

    public void setDescriptionDefault(){
        jl_DescriptionHeading.setText("Skill Name");
        jta_DescriptionBody.setText("");
        jta_DescriptionBody_SP.setText("");
    }
    public String skillPoint(Skill skill){
        return "SkillPoint : " + skill.skillPoint;
    }
    public void initDeck(){
        int x = 11, y = 13;
        for(int i = 0; i < deck.length; i++){
            deck[i] = new Deck();
            deck[i].setBounds(x,y, 114, 114);
            jp_ListOfDeck.add(deck[i]);
            x+= 125;
        }
    }
    public void initCard(){
        int x = 30, y= 30;
        for(int i = 0; i < Skill.list.length; i++){
            card[i] = new SkillCard(Skill.list[i]);
            card[i].setBounds(x, y, 114, 114);
            jp_ListOfCard.add(card[i]);
            x+= 140;
            if (x > 500){
                x = 30;
                y += 140;
            }
        }
    }
    
    private void changeTo(JPanel jp)
    {
        jp_Background.removeAll();
        jp_Background.add(jp);
        
        jp_Background.repaint();
        jp_Background.revalidate();
    }
    
    private void jp_PlayButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_PlayButtonMouseClicked
        changeTo(jp_PlayMenu);
        jp_MenuButtonBlack(evt);
    }//GEN-LAST:event_jp_PlayButtonMouseClicked

    private void jp_MenuButtonWhite(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_MenuButtonWhite
        // TODO add your handling code here:
        if(evt.getSource() instanceof JPanel jp)
        {
            ((JLabel)jp.getComponent(0)).setForeground(Color.BLACK);
            jp.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jp_MenuButtonWhite

    private void jp_MenuButtonBlack(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_MenuButtonBlack
        // TODO add your handling code here:
        if(evt.getSource() instanceof JPanel jp)
        {
            ((JLabel)jp.getComponent(0)).setForeground(Color.WHITE);
            jp.setBackground(Color.BLACK);
        }
    }//GEN-LAST:event_jp_MenuButtonBlack

    private void jp_ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_ExitButtonMouseClicked
        // TODO add your handling code here:
        jp_MenuButtonBlack(evt);
        
//        switch(JOptionPane.showConfirmDialog(this,"Are you sure want to exit?","WARNING!", JOptionPane.YES_NO_OPTION, JOptionPane.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT)){
//            case 0 -> {
//                System.exit(0);
//            }
//        }

        changeTo(jp_ExitConfirmation);
    }//GEN-LAST:event_jp_ExitButtonMouseClicked

    private void jp_DeckButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_DeckButtonMouseClicked
        // TODO add your handling code here:
        changeTo(jp_DeckMenu);
        jp_MenuButtonBlack(evt);
    }//GEN-LAST:event_jp_DeckButtonMouseClicked

    private void jp_HelpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_HelpButtonMouseClicked
        // TODO add your handling code here:
        changeTo(jp_HelpMenu);
        jp_MenuButtonBlack(evt);
    }//GEN-LAST:event_jp_HelpButtonMouseClicked

    private void jp_changeAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_changeAccMouseClicked
        // TODO add your handling code here:
        /*
        jp_MainMenu.removeAll();
        jp_MainMenu.repaint();
        jp_MainMenu.revalidate();
        jp_MainMenu.add(new Popup());
        jp_MainMenu.add(jl_AccountName);
        jp_MainMenu.add(jp_PlayButton);
        jp_MainMenu.add(jp_HelpButton);
        jp_MainMenu.add(jp_DeckButton);
        jp_MainMenu.add(jp_OptionButton);
        jp_MainMenu.add(jp_changeAcc);
        jp_MainMenu.add(jp_ExitButton);
        jp_MainMenu.repaint();
        jp_MainMenu.revalidate();
        */
        
//        String x = JOptionPane.showInputDialog(this, "Inpur your Name", "Account", JOptionPane.UNDEFINED_CONDITION);
//        Account temp = activeAccount;
//        activeAccount = null;
//        if(x == null){
//            activeAccount = temp;
//            return;
//        }if(x.equals("")){
//            JOptionPane.showMessageDialog(this, "No Username found!", "WARNING!", JOptionPane.ERROR_MESSAGE);
//            activeAccount = temp;
//            return;
//        }
//        for(Account i : accounts){
//            if(i.username.equals(x)){
//                activeAccount = i;
//                JOptionPane.showMessageDialog(this, "Welcome, " + i.username);
//                setActiveAccount(i);
//                return;
//            }
//        }
//        if(activeAccount == null){
//            JOptionPane.showMessageDialog(this, "Hai, "+ x, "Account Registered", JOptionPane.INFORMATION_MESSAGE);
//            accounts.add(new Account(x));
//            activeAccount = accounts.get(accounts.size()-1);
//            setActiveAccount(activeAccount);
//        }
        jp_MenuButtonWhite(evt);
        jcb_ChooseAccount.removeAllItems();
        for (Account a : accounts) {
            jcb_ChooseAccount.addItem(a.username);
        }
        changeTo(jp_ChangeAccount);
        
    }//GEN-LAST:event_jp_changeAccMouseClicked

    private void jp_OptionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_OptionButtonMouseClicked
        // TODO add your handling code here:
        changeTo(jp_OptionMenu);
        jp_MenuButtonBlack(evt);
        //jta_DescriptionBody.setToolTipText("No Description");
    }//GEN-LAST:event_jp_OptionButtonMouseClicked

    private void jp_BackOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_BackOptionMouseClicked
        jp_MenuButtonBlack(evt);
        // TODO add your handling code here:
        changeTo(jp_MainMenu);
    }//GEN-LAST:event_jp_BackOptionMouseClicked

    private void jp_BackHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_BackHelpMouseClicked
        // TODO add your handling code here:
        jp_MenuButtonBlack(evt);
        changeTo(jp_MainMenu);
    }//GEN-LAST:event_jp_BackHelpMouseClicked

    private void jp_BackDeckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_BackDeckMouseClicked
        // TODO add your handling code here:
        jp_MenuButtonBlack(evt);
        activeAccount.isiDeck(deck);
        //activeAccount.testIsiDeck();
        
        changeTo(jp_MainMenu);
        setDescriptionDefault();
    }//GEN-LAST:event_jp_BackDeckMouseClicked

    private void jp_PlayLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_PlayLogoMouseClicked
        // TODO add your handling code here:
        jp_PlayMenu.add(new Popup());
        jp_PlayMenu.repaint();
        jp_PlayMenu.revalidate();
        System.out.println("clicked");
    }//GEN-LAST:event_jp_PlayLogoMouseClicked

    private void jp_ExitOKButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_ExitOKButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jp_ExitOKButtonMouseClicked

    private void jp_ExitOKButtonPoppupButtonEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_ExitOKButtonPoppupButtonEntered
        // TODO add your handling code here:
        if(evt.getSource() instanceof JPanel jp)
        {
            ((JLabel)jp.getComponent(0)).setForeground(Color.WHITE);
            jp.setBackground(Color.BLACK);
        }
    }//GEN-LAST:event_jp_ExitOKButtonPoppupButtonEntered

    private void jp_ExitOKButtonPoppupButtonExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_ExitOKButtonPoppupButtonExited
        // TODO add your handling code here:
        if(evt.getSource() instanceof JPanel jp)
        {
            ((JLabel)jp.getComponent(0)).setForeground(Color.BLACK);
            jp.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jp_ExitOKButtonPoppupButtonExited

    private void jp_ExitCancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_ExitCancelButtonMouseClicked
        // TODO add your handling code here:
        jp_MenuButtonWhite(evt);
        changeTo(jp_MainMenu);
    }//GEN-LAST:event_jp_ExitCancelButtonMouseClicked

    private void jp_ExitCancelButtonPoppupButtonEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_ExitCancelButtonPoppupButtonEntered
        // TODO add your handling code here:
        if(evt.getSource() instanceof JPanel jp)
        {
            ((JLabel)jp.getComponent(0)).setForeground(Color.WHITE);
            jp.setBackground(Color.BLACK);
        }
    }//GEN-LAST:event_jp_ExitCancelButtonPoppupButtonEntered

    private void jp_ExitCancelButtonPoppupButtonExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_ExitCancelButtonPoppupButtonExited
        // TODO add your handling code here:
        if(evt.getSource() instanceof JPanel jp)
        {
            ((JLabel)jp.getComponent(0)).setForeground(Color.BLACK);
            jp.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jp_ExitCancelButtonPoppupButtonExited

    private void jp_VolumeUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_VolumeUpMouseClicked
        // TODO add your handling code here:
        volumeUp(0.1);
    }//GEN-LAST:event_jp_VolumeUpMouseClicked

    private void jp_VolumeDownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_VolumeDownMouseClicked
        // TODO add your handling code here:
        volumeDown(0.1);
    }//GEN-LAST:event_jp_VolumeDownMouseClicked

    private void jp_MaxButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_MaxButtonMouseClicked
        // TODO add your handling code here:
        volumeControl(1.0);
    }//GEN-LAST:event_jp_MaxButtonMouseClicked

    private void jp_MinButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_MinButtonMouseClicked
        // TODO add your handling code here:
        volumeControl(0.0);
    }//GEN-LAST:event_jp_MinButtonMouseClicked
    private void jp_CreateAccountButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_CreateAccountButtonMouseClicked
        // TODO add your handling code here:
        jp_MenuButtonWhite(evt);
        String str = jtf_AccountName.getText();
        boolean exists = false;
        
        for (Account a : accounts) 
        {
            if(a.username.equals(str))
            {
                exists = true;
                break;
            }
        }
        
        if(!str.isBlank() && !exists)
        {
            Account a = new Account(str);
            accounts.add(a);
            setActiveAccount(a);
            changeTo(jp_MainMenu);
            jl_CreateAccountFailed.setText(" ");
            jtf_AccountName.setText("");
        }
        else
        {
            if(exists)
            {
                jl_CreateAccountFailed.setText("This username already exists");
            }
            else if(str.isBlank())
            {
                jl_CreateAccountFailed.setText("The username cannot be empty");
            }
        }
        
    }//GEN-LAST:event_jp_CreateAccountButtonMouseClicked

    private void jp_ChangeAccountSelectButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_ChangeAccountSelectButtonMouseClicked
        // TODO add your handling code here:
        jp_MenuButtonWhite(evt);
        setActiveAccount(accounts.get(jcb_ChooseAccount.getSelectedIndex()));
        changeTo(jp_MainMenu);
    }//GEN-LAST:event_jp_ChangeAccountSelectButtonMouseClicked

    private void jp_ChangeAccountCreateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_ChangeAccountCreateButtonMouseClicked
        // TODO add your handling code here:
        jp_MenuButtonWhite(evt);
        changeTo(jp_CreateAccount);
    }//GEN-LAST:event_jp_ChangeAccountCreateButtonMouseClicked

    
    private void setDescription(Skill x){
        jl_DescriptionHeading.setText(x.name);
        jta_DescriptionBody.setText(x.toString());
        jta_DescriptionBody_SP.setText(skillPoint(x));
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Program program;
            try {
                program = new Program();
                program.fullScreen();
            } catch (IOException ex) {
                Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Ini error");
            } catch (UnsupportedAudioFileException ex) {
                Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
            } catch (LineUnavailableException ex) {
                Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Help_desc;
    private mgw.main.GameUI gameUI1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcb_ChooseAccount;
    private javax.swing.JLabel jl_AccountName;
    private javax.swing.JLabel jl_BackDeck;
    private javax.swing.JLabel jl_BackHelp;
    private javax.swing.JLabel jl_BackOption;
    private javax.swing.JLabel jl_ChangeAccountCreateButton;
    private javax.swing.JLabel jl_ChangeAccountSelectButton;
    private javax.swing.JLabel jl_CreateAccountButton;
    private javax.swing.JLabel jl_CreateAccountFailed;
    private javax.swing.JLabel jl_Deck;
    private javax.swing.JLabel jl_DescriptionHeading;
    private javax.swing.JLabel jl_Exit;
    private javax.swing.JLabel jl_ExitCancel;
    private javax.swing.JLabel jl_ExitConfirmation;
    private javax.swing.JLabel jl_ExitOk;
    private javax.swing.JLabel jl_Help;
    private javax.swing.JLabel jl_JudulDesk;
    private javax.swing.JLabel jl_Max;
    private javax.swing.JLabel jl_Min;
    private javax.swing.JLabel jl_Option;
    private javax.swing.JLabel jl_Play;
    private javax.swing.JLabel jl_Volume;
    private javax.swing.JLabel jl_VolumeDown;
    private javax.swing.JLabel jl_VolumeUp;
    private javax.swing.JLabel jl_changeAcc;
    private javax.swing.JPanel jp_BackDeck;
    private javax.swing.JPanel jp_BackHelp;
    private javax.swing.JPanel jp_BackOption;
    private javax.swing.JPanel jp_Background;
    private javax.swing.JPanel jp_BodyHelp;
    private javax.swing.JPanel jp_ChangeAccount;
    private javax.swing.JPanel jp_ChangeAccountCreateButton;
    private javax.swing.JPanel jp_ChangeAccountSelectButton;
    private javax.swing.JPanel jp_CreateAccount;
    private javax.swing.JPanel jp_CreateAccountButton;
    private javax.swing.JPanel jp_DeckButton;
    private javax.swing.JPanel jp_DeckMenu;
    private javax.swing.JPanel jp_DescriptionBody;
    private javax.swing.JPanel jp_ExitButton;
    private javax.swing.JPanel jp_ExitCancelButton;
    private javax.swing.JPanel jp_ExitConfirmation;
    private javax.swing.JPanel jp_ExitOKButton;
    private javax.swing.JPanel jp_HelpButton;
    private javax.swing.JPanel jp_HelpMenu;
    private javax.swing.JPanel jp_JudulDesk;
    private javax.swing.JPanel jp_ListOfCard;
    private javax.swing.JPanel jp_ListOfDeck;
    public static javax.swing.JPanel jp_MainMenu;
    private javax.swing.JPanel jp_MaxButton;
    private javax.swing.JPanel jp_MinButton;
    private javax.swing.JPanel jp_OptionButton;
    private javax.swing.JPanel jp_OptionMenu;
    private javax.swing.JPanel jp_PlayButton;
    private javax.swing.JPanel jp_PlayMenu;
    private javax.swing.JPanel jp_SkillDesc;
    private javax.swing.JPanel jp_Volume;
    private javax.swing.JPanel jp_VolumeDown;
    private javax.swing.JPanel jp_VolumeUp;
    private javax.swing.JPanel jp_changeAcc;
    private javax.swing.JTextArea jta_DescriptionBody;
    private javax.swing.JTextArea jta_DescriptionBody_SP;
    private javax.swing.JTextField jtf_AccountName;
    private javax.swing.JLabel lb_ChangeAccount;
    private javax.swing.JLabel lb_CreateAccount;
    // End of variables declaration//GEN-END:variables

   

}
