package mgw.main;


import javax.swing.JFrame;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.*;
import mgw.gameplay.Skill;

public final class Program extends javax.swing.JFrame{

    static GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
    ArrayList<Account> akun = new ArrayList<>();
    Image skill[] = new Image[14];
    Card card[] = new Card[Skill.list.length];
    Deck deck[] = new Deck[5];
    Account active[] = new Account[1];
    int [] arr = new int[1];
    /**
     * Creates new form Program
     */
    public Program() {
        this.setUndecorated(true);
        initComponents();
        initCard();
        checkCard();
        initDeck();
        checkDeck();
        akun.add(new Account("Yurtan"));
        active[0] = akun.get(0);
        welcomeAkun(active[0]);
    }
    
    public final void fullScreen()
    {
        this.setResizable(false);
        gd.setFullScreenWindow(this);
    }
    public void welcomeAkun(Account x){
        jl_AccountName.setText("Haii " + x.toString());
    }
   
    public void checkCard(){
        for (Card card1 : card) {
            card1.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    cardClicked(evt);
                }
                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    cardEntered(evt);
                }
                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    cardExited(evt);
                }
            });
        }
    }
    public void checkDeck(){
        for (Deck deck1 : deck) {
            deck1.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    deckClicked(evt);
                }
                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    deckEntered(evt);
                }
                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    deckExited(evt);
                }
            });
        }
    }
    public void deckClicked(java.awt.event.MouseEvent evt){
        if(evt.getSource() instanceof Deck d){
            if(!d.empty){
                d.deckRemove(card);
            }
        }
    }
    public void deckEntered(java.awt.event.MouseEvent evt){
        if(evt.getSource() instanceof Deck d){
            
        }
    }
    public void deckExited(java.awt.event.MouseEvent evt){
        if(evt.getSource() instanceof Deck d){
            
        }
    }
    
    private void cardClicked(java.awt.event.MouseEvent evt){
        if(evt.getSource() instanceof Card c){
            if(c.clicked)
                return;
            if(Deck.counter > 5)
                return;
            for(Deck i : deck)
                if(i.skill == null){
                    i.deckCopy(c);
                    return;
                }
        }
    }
    
    private void cardEntered(java.awt.event.MouseEvent evt){
        if(evt.getSource() instanceof Card c)
        {
            setDescription(c.skill);
        }
        
    }
    private void cardExited(java.awt.event.MouseEvent evt){
        if(evt.getSource() instanceof Card c)
        {
            setDescriptionDefault();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jp_Background = new javax.swing.JPanel();
        jp_MainMenu = new javax.swing.JPanel();
        jl_AccountName = new javax.swing.JLabel();
        jp_PlayButton = new javax.swing.JPanel();
        jl_Play = new javax.swing.JLabel();
        jp_DeckButton = new javax.swing.JPanel();
        jl_Deck = new javax.swing.JLabel();
        jp_HelpButton = new javax.swing.JPanel();
        jl_Help = new javax.swing.JLabel();
        jp_OptionButton = new javax.swing.JPanel();
        jl_Option = new javax.swing.JLabel();
        jp_ExitButton = new javax.swing.JPanel();
        jl_Exit = new javax.swing.JLabel();
        jp_changeAcc = new javax.swing.JPanel();
        jl_changeAcc = new javax.swing.JLabel();
        jp_PlayMenu = new javax.swing.JPanel();
        jp_PlayLogo = new javax.swing.JPanel();
        jl_PlayLogo = new javax.swing.JLabel();
        jp_BackPlay = new javax.swing.JPanel();
        jl_BackPlay = new javax.swing.JLabel();
        jp_DeckMenu = new javax.swing.JPanel();
        jp_BackDeck = new javax.swing.JPanel();
        jl_BackDeck = new javax.swing.JLabel();
        jp_ListOfCard = new javax.swing.JPanel();
        jp_SkillDesc = new javax.swing.JPanel();
        jp_DescriptionBody = new javax.swing.JPanel();
        jta_DescriptionBody = new javax.swing.JTextArea();
        jta_DescriptionBody_SP = new javax.swing.JTextArea();
        jp_ListOfDeck = new javax.swing.JPanel();
        jp_DescriptionHeading = new javax.swing.JPanel();
        jl_DescriptionHeading = new javax.swing.JLabel();
        jp_HelpMenu = new javax.swing.JPanel();
        jp_PlayLogo2 = new javax.swing.JPanel();
        jl_PlayLogo2 = new javax.swing.JLabel();
        jp_BackHelp = new javax.swing.JPanel();
        jl_BackHelp = new javax.swing.JLabel();
        jp_OptionMenu = new javax.swing.JPanel();
        jp_BackOption = new javax.swing.JPanel();
        jl_BackOption = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_Background.setBackground(new java.awt.Color(102, 102, 102));
        jp_Background.setLayout(new java.awt.CardLayout());

        jp_MainMenu.setBackground(new java.awt.Color(0, 0, 0));

        jl_AccountName.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jl_AccountName.setForeground(new java.awt.Color(255, 255, 255));
        jl_AccountName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jl_AccountName.setText("welcome,yurtan");

        jp_PlayButton.setBackground(new java.awt.Color(0, 0, 0));
        jp_PlayButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jp_PlayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_PlayButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_ExitButtonMouseExited(evt);
            }
        });

        jl_Play.setBackground(new java.awt.Color(255, 255, 255));
        jl_Play.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_Play.setForeground(new java.awt.Color(255, 255, 255));
        jl_Play.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Play.setText("PLAY");

        javax.swing.GroupLayout jp_PlayButtonLayout = new javax.swing.GroupLayout(jp_PlayButton);
        jp_PlayButton.setLayout(jp_PlayButtonLayout);
        jp_PlayButtonLayout.setHorizontalGroup(
            jp_PlayButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jp_PlayButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jl_Play, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
        );
        jp_PlayButtonLayout.setVerticalGroup(
            jp_PlayButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
            .addGroup(jp_PlayButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_PlayButtonLayout.createSequentialGroup()
                    .addComponent(jl_Play)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jp_DeckButton.setBackground(new java.awt.Color(0, 0, 0));
        jp_DeckButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_DeckButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_ExitButtonMouseExited(evt);
            }
        });

        jl_Deck.setBackground(new java.awt.Color(255, 255, 255));
        jl_Deck.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_Deck.setForeground(new java.awt.Color(255, 255, 255));
        jl_Deck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Deck.setText("DECK");

        javax.swing.GroupLayout jp_DeckButtonLayout = new javax.swing.GroupLayout(jp_DeckButton);
        jp_DeckButton.setLayout(jp_DeckButtonLayout);
        jp_DeckButtonLayout.setHorizontalGroup(
            jp_DeckButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Deck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_DeckButtonLayout.setVerticalGroup(
            jp_DeckButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Deck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jp_HelpButton.setBackground(new java.awt.Color(0, 0, 0));
        jp_HelpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_HelpButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_ExitButtonMouseExited(evt);
            }
        });

        jl_Help.setBackground(new java.awt.Color(255, 255, 255));
        jl_Help.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_Help.setForeground(new java.awt.Color(255, 255, 255));
        jl_Help.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Help.setText("HELP");
        jl_Help.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jp_HelpButtonLayout = new javax.swing.GroupLayout(jp_HelpButton);
        jp_HelpButton.setLayout(jp_HelpButtonLayout);
        jp_HelpButtonLayout.setHorizontalGroup(
            jp_HelpButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_HelpButtonLayout.createSequentialGroup()
                .addComponent(jl_Help, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jp_HelpButtonLayout.setVerticalGroup(
            jp_HelpButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Help, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jp_OptionButton.setBackground(new java.awt.Color(0, 0, 0));
        jp_OptionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_OptionButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_ExitButtonMouseExited(evt);
            }
        });

        jl_Option.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_Option.setForeground(new java.awt.Color(255, 255, 255));
        jl_Option.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Option.setText("OPTION");

        javax.swing.GroupLayout jp_OptionButtonLayout = new javax.swing.GroupLayout(jp_OptionButton);
        jp_OptionButton.setLayout(jp_OptionButtonLayout);
        jp_OptionButtonLayout.setHorizontalGroup(
            jp_OptionButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Option, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_OptionButtonLayout.setVerticalGroup(
            jp_OptionButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_OptionButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jl_Option))
        );

        jp_ExitButton.setBackground(new java.awt.Color(0, 0, 0));
        jp_ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_ExitButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_MenuButtonEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_ExitButtonMouseExited(evt);
            }
        });

        jl_Exit.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_Exit.setForeground(new java.awt.Color(255, 255, 255));
        jl_Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Exit.setText("EXIT");

        javax.swing.GroupLayout jp_ExitButtonLayout = new javax.swing.GroupLayout(jp_ExitButton);
        jp_ExitButton.setLayout(jp_ExitButtonLayout);
        jp_ExitButtonLayout.setHorizontalGroup(
            jp_ExitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_ExitButtonLayout.setVerticalGroup(
            jp_ExitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_ExitButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jl_Exit))
        );

        jp_changeAcc.setBackground(new java.awt.Color(255, 255, 255));
        jp_changeAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_changeAccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_changeAccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_changeAccMouseExited(evt);
            }
        });

        jl_changeAcc.setBackground(new java.awt.Color(0, 0, 0));
        jl_changeAcc.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_changeAcc.setForeground(new java.awt.Color(0, 0, 0));
        jl_changeAcc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_changeAcc.setText("Change Account");

        javax.swing.GroupLayout jp_changeAccLayout = new javax.swing.GroupLayout(jp_changeAcc);
        jp_changeAcc.setLayout(jp_changeAccLayout);
        jp_changeAccLayout.setHorizontalGroup(
            jp_changeAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_changeAccLayout.createSequentialGroup()
                .addComponent(jl_changeAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jp_changeAccLayout.setVerticalGroup(
            jp_changeAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_changeAcc, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jp_MainMenuLayout = new javax.swing.GroupLayout(jp_MainMenu);
        jp_MainMenu.setLayout(jp_MainMenuLayout);
        jp_MainMenuLayout.setHorizontalGroup(
            jp_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_MainMenuLayout.createSequentialGroup()
                .addGroup(jp_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jp_ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_PlayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_OptionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_DeckButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_HelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(705, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_MainMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jp_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_MainMenuLayout.createSequentialGroup()
                        .addComponent(jp_changeAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_MainMenuLayout.createSequentialGroup()
                        .addComponent(jl_AccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jp_MainMenuLayout.setVerticalGroup(
            jp_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_MainMenuLayout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(jp_PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jp_DeckButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jp_OptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jp_HelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jp_ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(jl_AccountName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_changeAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jp_Background.add(jp_MainMenu, "card2");

        jl_PlayLogo.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jl_PlayLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_PlayLogo.setText("PLAY");

        javax.swing.GroupLayout jp_PlayLogoLayout = new javax.swing.GroupLayout(jp_PlayLogo);
        jp_PlayLogo.setLayout(jp_PlayLogoLayout);
        jp_PlayLogoLayout.setHorizontalGroup(
            jp_PlayLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_PlayLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );
        jp_PlayLogoLayout.setVerticalGroup(
            jp_PlayLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_PlayLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jp_BackPlay.setBackground(new java.awt.Color(0, 0, 0));
        jp_BackPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_BackPlayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_BackPlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_BackPlayMouseExited(evt);
            }
        });

        jl_BackPlay.setBackground(new java.awt.Color(255, 255, 255));
        jl_BackPlay.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_BackPlay.setForeground(new java.awt.Color(255, 255, 255));
        jl_BackPlay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_BackPlay.setText("back");
        jl_BackPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_BackPlayMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_BackPlayLayout = new javax.swing.GroupLayout(jp_BackPlay);
        jp_BackPlay.setLayout(jp_BackPlayLayout);
        jp_BackPlayLayout.setHorizontalGroup(
            jp_BackPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_BackPlay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );
        jp_BackPlayLayout.setVerticalGroup(
            jp_BackPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_BackPlay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jp_PlayMenuLayout = new javax.swing.GroupLayout(jp_PlayMenu);
        jp_PlayMenu.setLayout(jp_PlayMenuLayout);
        jp_PlayMenuLayout.setHorizontalGroup(
            jp_PlayMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_PlayMenuLayout.createSequentialGroup()
                .addContainerGap(472, Short.MAX_VALUE)
                .addComponent(jp_PlayLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
            .addGroup(jp_PlayMenuLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jp_BackPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_PlayMenuLayout.setVerticalGroup(
            jp_PlayMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_PlayMenuLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jp_PlayLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE)
                .addComponent(jp_BackPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jp_Background.add(jp_PlayMenu, "card3");

        jp_BackDeck.setBackground(new java.awt.Color(0, 0, 0));
        jp_BackDeck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_BackDeckMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_BackDeckMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_BackDeckMouseExited(evt);
            }
        });

        jl_BackDeck.setBackground(new java.awt.Color(255, 255, 255));
        jl_BackDeck.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_BackDeck.setForeground(new java.awt.Color(255, 255, 255));
        jl_BackDeck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_BackDeck.setText("back");

        javax.swing.GroupLayout jp_BackDeckLayout = new javax.swing.GroupLayout(jp_BackDeck);
        jp_BackDeck.setLayout(jp_BackDeckLayout);
        jp_BackDeckLayout.setHorizontalGroup(
            jp_BackDeckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_BackDeck, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );
        jp_BackDeckLayout.setVerticalGroup(
            jp_BackDeckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_BackDeck, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jp_ListOfCard.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jp_ListOfCardLayout = new javax.swing.GroupLayout(jp_ListOfCard);
        jp_ListOfCard.setLayout(jp_ListOfCardLayout);
        jp_ListOfCardLayout.setHorizontalGroup(
            jp_ListOfCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jp_ListOfCardLayout.setVerticalGroup(
            jp_ListOfCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        jta_DescriptionBody.setEditable(false);
        jta_DescriptionBody.setColumns(20);
        jta_DescriptionBody.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jta_DescriptionBody.setLineWrap(true);
        jta_DescriptionBody.setRows(5);
        jta_DescriptionBody.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jta_DescriptionBody_SP.setEditable(false);
        jta_DescriptionBody_SP.setColumns(20);
        jta_DescriptionBody_SP.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jta_DescriptionBody_SP.setLineWrap(true);
        jta_DescriptionBody_SP.setRows(5);
        jta_DescriptionBody_SP.setAutoscrolls(false);

        javax.swing.GroupLayout jp_DescriptionBodyLayout = new javax.swing.GroupLayout(jp_DescriptionBody);
        jp_DescriptionBody.setLayout(jp_DescriptionBodyLayout);
        jp_DescriptionBodyLayout.setHorizontalGroup(
            jp_DescriptionBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jta_DescriptionBody_SP, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jta_DescriptionBody, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jp_DescriptionBodyLayout.setVerticalGroup(
            jp_DescriptionBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_DescriptionBodyLayout.createSequentialGroup()
                .addComponent(jta_DescriptionBody)
                .addGap(20, 20, 20)
                .addComponent(jta_DescriptionBody_SP, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jp_SkillDescLayout = new javax.swing.GroupLayout(jp_SkillDesc);
        jp_SkillDesc.setLayout(jp_SkillDescLayout);
        jp_SkillDescLayout.setHorizontalGroup(
            jp_SkillDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_SkillDescLayout.createSequentialGroup()
                .addComponent(jp_DescriptionBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jp_SkillDescLayout.setVerticalGroup(
            jp_SkillDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_DescriptionBody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jp_ListOfDeck.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jp_ListOfDeckLayout = new javax.swing.GroupLayout(jp_ListOfDeck);
        jp_ListOfDeck.setLayout(jp_ListOfDeckLayout);
        jp_ListOfDeckLayout.setHorizontalGroup(
            jp_ListOfDeckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jp_ListOfDeckLayout.setVerticalGroup(
            jp_ListOfDeckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        jl_DescriptionHeading.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jl_DescriptionHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_DescriptionHeading.setText("Skill Name");

        javax.swing.GroupLayout jp_DescriptionHeadingLayout = new javax.swing.GroupLayout(jp_DescriptionHeading);
        jp_DescriptionHeading.setLayout(jp_DescriptionHeadingLayout);
        jp_DescriptionHeadingLayout.setHorizontalGroup(
            jp_DescriptionHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_DescriptionHeadingLayout.createSequentialGroup()
                .addComponent(jl_DescriptionHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jp_DescriptionHeadingLayout.setVerticalGroup(
            jp_DescriptionHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_DescriptionHeading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jp_DeckMenuLayout = new javax.swing.GroupLayout(jp_DeckMenu);
        jp_DeckMenu.setLayout(jp_DeckMenuLayout);
        jp_DeckMenuLayout.setHorizontalGroup(
            jp_DeckMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_DeckMenuLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jp_BackDeck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jp_ListOfDeck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jp_DeckMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jp_ListOfCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_DeckMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_DeckMenuLayout.createSequentialGroup()
                        .addComponent(jp_DescriptionHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jp_DeckMenuLayout.createSequentialGroup()
                        .addComponent(jp_SkillDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(101, 101, 101))))
        );
        jp_DeckMenuLayout.setVerticalGroup(
            jp_DeckMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_DeckMenuLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jp_DescriptionHeading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jp_DeckMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_ListOfCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_SkillDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jp_DeckMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_DeckMenuLayout.createSequentialGroup()
                        .addComponent(jp_BackDeck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_DeckMenuLayout.createSequentialGroup()
                        .addComponent(jp_ListOfDeck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jp_Background.add(jp_DeckMenu, "card3");

        jl_PlayLogo2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jl_PlayLogo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_PlayLogo2.setText("PLAY");

        javax.swing.GroupLayout jp_PlayLogo2Layout = new javax.swing.GroupLayout(jp_PlayLogo2);
        jp_PlayLogo2.setLayout(jp_PlayLogo2Layout);
        jp_PlayLogo2Layout.setHorizontalGroup(
            jp_PlayLogo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_PlayLogo2, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );
        jp_PlayLogo2Layout.setVerticalGroup(
            jp_PlayLogo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_PlayLogo2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jp_BackHelp.setBackground(new java.awt.Color(0, 0, 0));
        jp_BackHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_BackHelpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_BackHelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_BackHelpMouseExited(evt);
            }
        });

        jl_BackHelp.setBackground(new java.awt.Color(255, 255, 255));
        jl_BackHelp.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_BackHelp.setForeground(new java.awt.Color(255, 255, 255));
        jl_BackHelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_BackHelp.setText("back");

        javax.swing.GroupLayout jp_BackHelpLayout = new javax.swing.GroupLayout(jp_BackHelp);
        jp_BackHelp.setLayout(jp_BackHelpLayout);
        jp_BackHelpLayout.setHorizontalGroup(
            jp_BackHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_BackHelp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );
        jp_BackHelpLayout.setVerticalGroup(
            jp_BackHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_BackHelp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jp_HelpMenuLayout = new javax.swing.GroupLayout(jp_HelpMenu);
        jp_HelpMenu.setLayout(jp_HelpMenuLayout);
        jp_HelpMenuLayout.setHorizontalGroup(
            jp_HelpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_HelpMenuLayout.createSequentialGroup()
                .addContainerGap(472, Short.MAX_VALUE)
                .addComponent(jp_PlayLogo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
            .addGroup(jp_HelpMenuLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jp_BackHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_HelpMenuLayout.setVerticalGroup(
            jp_HelpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_HelpMenuLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jp_PlayLogo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addComponent(jp_BackHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jp_Background.add(jp_HelpMenu, "card3");

        jp_BackOption.setBackground(new java.awt.Color(0, 0, 0));
        jp_BackOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_BackOptionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_BackOptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_BackOptionMouseExited(evt);
            }
        });

        jl_BackOption.setBackground(new java.awt.Color(255, 255, 255));
        jl_BackOption.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_BackOption.setForeground(new java.awt.Color(255, 255, 255));
        jl_BackOption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_BackOption.setText("back");

        javax.swing.GroupLayout jp_BackOptionLayout = new javax.swing.GroupLayout(jp_BackOption);
        jp_BackOption.setLayout(jp_BackOptionLayout);
        jp_BackOptionLayout.setHorizontalGroup(
            jp_BackOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_BackOption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );
        jp_BackOptionLayout.setVerticalGroup(
            jp_BackOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_BackOption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jp_OptionMenuLayout = new javax.swing.GroupLayout(jp_OptionMenu);
        jp_OptionMenu.setLayout(jp_OptionMenuLayout);
        jp_OptionMenuLayout.setHorizontalGroup(
            jp_OptionMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_OptionMenuLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jp_BackOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(840, Short.MAX_VALUE))
        );
        jp_OptionMenuLayout.setVerticalGroup(
            jp_OptionMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_OptionMenuLayout.createSequentialGroup()
                .addContainerGap(575, Short.MAX_VALUE)
                .addComponent(jp_BackOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        jp_Background.add(jp_OptionMenu, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1009, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp_Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setColor(JPanel p, JLabel x){
        p.setBackground(Color.WHITE);
        x.setForeground(Color.BLACK);
    }
    public void resetColor(JPanel p, JLabel l){
        p.setBackground(Color.BLACK);
        l.setForeground(Color.WHITE);
    }
    public void setDescriptionDefault(){
        jl_DescriptionHeading.setText("Skill Name");
        jta_DescriptionBody.setText("");
        jta_DescriptionBody_SP.setText("");
    }
    public String skillPoint(Skill skill){
        return "SkillPoint = " + skill.skillPoint;
    }
    public void initDeck(){
        int x = 5, y = 13;
        for(int i = 0; i < deck.length; i++){
            deck[i] = new Deck();
            deck[i].setBounds(x,y, 114, 114);
            jp_ListOfDeck.add(deck[i]);
            x+= 125;
        }
    }
    public void initCard(){
        int x = 30, y= 30;
        for(int i = 0; i < Skill.list.length; i++){
            card[i] = new Card(Skill.list[i]);
            card[i].setBounds(x, y, 114, 114);
            jp_ListOfCard.add(card[i]);
            x+= 140;
            if (x > 500){
                x = 30;
                y += 140;
            }
        }
    }
    
    public void cardDesc(int x){
        jl_DescriptionHeading.setText(Skill.list[x].name);
        jta_DescriptionBody.setText(Skill.list[x].toString());
        jta_DescriptionBody_SP.setText("SkillPoint = " + Skill.list[x].skillPoint);
    }
    private void jp_changeAccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_changeAccMouseEntered
        resetColor(jp_changeAcc, jl_changeAcc);
    }//GEN-LAST:event_jp_changeAccMouseEntered

    private void jp_changeAccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_changeAccMouseExited
        setColor(jp_changeAcc, jl_changeAcc);
    }//GEN-LAST:event_jp_changeAccMouseExited

    private void jp_PlayButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_PlayButtonMouseClicked
        jp_Background.removeAll();
        jp_Background.repaint();
        jp_Background.revalidate();
        jp_Background.add(jp_PlayMenu);
        jp_Background.repaint();
        jp_Background.revalidate();
        resetColor(jp_PlayButton, jl_Play);
    }//GEN-LAST:event_jp_PlayButtonMouseClicked

    private void jp_MenuButtonEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_MenuButtonEntered
        // TODO add your handling code here:
        if(evt.getSource() instanceof JPanel jp)
        {
            ((JLabel)jp.getComponent(0)).setForeground(Color.BLACK);
            jp.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jp_MenuButtonEntered

    private void jp_ExitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_ExitButtonMouseExited
        // TODO add your handling code here:
        if(evt.getSource() instanceof JPanel jp)
        {
            ((JLabel)jp.getComponent(0)).setForeground(Color.WHITE);
            jp.setBackground(Color.BLACK);
        }
    }//GEN-LAST:event_jp_ExitButtonMouseExited

    private void jp_ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_ExitButtonMouseClicked
        // TODO add your handling code here:
        switch(JOptionPane.showConfirmDialog(this,"Are you sure want to exit?","WARNING!", JOptionPane.YES_NO_OPTION, JOptionPane.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT)){
            case 0 -> {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_jp_ExitButtonMouseClicked

    private void jp_DeckButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_DeckButtonMouseClicked
        // TODO add your handling code here:
        jp_Background.removeAll();
        jp_Background.repaint();
        jp_Background.revalidate();
        jp_Background.add(jp_DeckMenu);
        jp_Background.repaint();
        jp_Background.revalidate();
        resetColor(jp_DeckButton, jl_Deck);
    }//GEN-LAST:event_jp_DeckButtonMouseClicked

    private void jp_HelpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_HelpButtonMouseClicked
        // TODO add your handling code here:
        jp_Background.removeAll();
        jp_Background.repaint();
        jp_Background.revalidate();
        jp_Background.add(jp_HelpMenu);
        jp_Background.repaint();
        jp_Background.revalidate();
        resetColor(jp_HelpButton, jl_Help);
    }//GEN-LAST:event_jp_HelpButtonMouseClicked

    private void jp_changeAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_changeAccMouseClicked
        // TODO add your handling code here:
        
        String x = JOptionPane.showInputDialog(this, "Inpur your Name", "Account", JOptionPane.UNDEFINED_CONDITION);
        active[0] = null;
        if(x == null)
            return;
        if(x.equals("")){
            JOptionPane.showMessageDialog(this, "No Username found!", "WARNING!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        for(Account i : akun){
            if(i.username.equals(x)){
                active[0] = i;
                JOptionPane.showMessageDialog(this, "Welcome, " + i.username);
                welcomeAkun(i);
                return;
            }
        }
        if(active[0] == null){
            JOptionPane.showMessageDialog(this, "Hai, "+ x, "Account Registered", JOptionPane.INFORMATION_MESSAGE);
            akun.add(new Account(x));
            welcomeAkun(akun.get(akun.size()-1));
        }
    }//GEN-LAST:event_jp_changeAccMouseClicked

    private void jp_OptionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_OptionButtonMouseClicked
        // TODO add your handling code here:
        jp_Background.removeAll();
        jp_Background.repaint();
        jp_Background.revalidate();
        jp_Background.add(jp_OptionMenu);
        jp_Background.repaint();
        jp_Background.revalidate();
        resetColor(jp_OptionButton, jl_Option);
        jta_DescriptionBody.setToolTipText("No Description");
    }//GEN-LAST:event_jp_OptionButtonMouseClicked

    private void jp_BackOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_BackOptionMouseClicked
        
        // TODO add your handling code here:
        jp_Background.removeAll();
        jp_Background.repaint();
        jp_Background.revalidate();
        jp_Background.add(jp_MainMenu);
        jp_Background.repaint();
        jp_Background.revalidate();
    }//GEN-LAST:event_jp_BackOptionMouseClicked

    private void jp_BackOptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_BackOptionMouseEntered
        // TODO add your handling code here:
        if(evt.getSource() instanceof JPanel jp)
        {
            ((JLabel)jp.getComponent(0)).setForeground(Color.BLACK);
            jp.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jp_BackOptionMouseEntered

    private void jp_BackOptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_BackOptionMouseExited
        // TODO add your handling code here:
        if(evt.getSource() instanceof JPanel jp)
        {
            ((JLabel)jp.getComponent(0)).setForeground(Color.WHITE);
            jp.setBackground(Color.BLACK);
        }
    }//GEN-LAST:event_jp_BackOptionMouseExited

    private void jp_BackHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_BackHelpMouseClicked
        // TODO add your handling code here:
        jp_Background.removeAll();
        jp_Background.repaint();
        jp_Background.revalidate();
        jp_Background.add(jp_MainMenu);
        jp_Background.repaint();
        jp_Background.revalidate();
    }//GEN-LAST:event_jp_BackHelpMouseClicked

    private void jp_BackHelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_BackHelpMouseEntered
        // TODO add your handling code here:
        if(evt.getSource() instanceof JPanel jp)
        {
            ((JLabel)jp.getComponent(0)).setForeground(Color.BLACK);
            jp.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jp_BackHelpMouseEntered

    private void jp_BackHelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_BackHelpMouseExited
        // TODO add your handling code here:
        if(evt.getSource() instanceof JPanel jp)
        {
            ((JLabel)jp.getComponent(0)).setForeground(Color.WHITE);
            jp.setBackground(Color.BLACK);
        }
    }//GEN-LAST:event_jp_BackHelpMouseExited

    private void jp_BackDeckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_BackDeckMouseClicked
        // TODO add your handling code here:
        active[0].isiDeck(deck);
        active[0].testIsiDeck();
        jp_Background.removeAll();
        jp_Background.repaint();
        jp_Background.revalidate();
        jp_Background.add(jp_MainMenu);
        jp_Background.repaint();
        jp_Background.revalidate();
        setDescriptionDefault();
    }//GEN-LAST:event_jp_BackDeckMouseClicked

    private void jp_BackDeckMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_BackDeckMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jp_BackDeckMouseEntered

    private void jp_BackDeckMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_BackDeckMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jp_BackDeckMouseExited

    private void jp_BackPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_BackPlayMouseClicked
        // TODO add your handling code here:
        jp_Background.removeAll();
        jp_Background.repaint();
        jp_Background.revalidate();
        jp_Background.add(jp_MainMenu);
        jp_Background.repaint();
        jp_Background.revalidate();
    }//GEN-LAST:event_jp_BackPlayMouseClicked

    private void jp_BackPlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_BackPlayMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jp_BackPlayMouseEntered

    private void jp_BackPlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_BackPlayMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jp_BackPlayMouseExited

    private void jl_BackPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_BackPlayMouseClicked
        // TODO add your handling code here:
        jp_Background.removeAll();
        jp_Background.repaint();
        jp_Background.revalidate();
        jp_Background.add(jp_MainMenu);
        jp_Background.repaint();
        jp_Background.revalidate();
    }//GEN-LAST:event_jl_BackPlayMouseClicked
    private void setDescription(Skill x){
        jl_DescriptionHeading.setText(x.name);
        jta_DescriptionBody.setText(x.toString());
        jta_DescriptionBody_SP.setText(skillPoint(x));
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Program program = new Program();
            program.fullScreen();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jl_AccountName;
    private javax.swing.JLabel jl_BackDeck;
    private javax.swing.JLabel jl_BackHelp;
    private javax.swing.JLabel jl_BackOption;
    private javax.swing.JLabel jl_BackPlay;
    private javax.swing.JLabel jl_Deck;
    private javax.swing.JLabel jl_DescriptionHeading;
    private javax.swing.JLabel jl_Exit;
    private javax.swing.JLabel jl_Help;
    private javax.swing.JLabel jl_Option;
    private javax.swing.JLabel jl_Play;
    private javax.swing.JLabel jl_PlayLogo;
    private javax.swing.JLabel jl_PlayLogo2;
    private javax.swing.JLabel jl_changeAcc;
    private javax.swing.JPanel jp_BackDeck;
    private javax.swing.JPanel jp_BackHelp;
    private javax.swing.JPanel jp_BackOption;
    private javax.swing.JPanel jp_BackPlay;
    private javax.swing.JPanel jp_Background;
    private javax.swing.JPanel jp_DeckButton;
    private javax.swing.JPanel jp_DeckMenu;
    private javax.swing.JPanel jp_DescriptionBody;
    private javax.swing.JPanel jp_DescriptionHeading;
    private javax.swing.JPanel jp_ExitButton;
    private javax.swing.JPanel jp_HelpButton;
    private javax.swing.JPanel jp_HelpMenu;
    private javax.swing.JPanel jp_ListOfCard;
    private javax.swing.JPanel jp_ListOfDeck;
    private javax.swing.JPanel jp_MainMenu;
    private javax.swing.JPanel jp_OptionButton;
    private javax.swing.JPanel jp_OptionMenu;
    private javax.swing.JPanel jp_PlayButton;
    private javax.swing.JPanel jp_PlayLogo;
    private javax.swing.JPanel jp_PlayLogo2;
    private javax.swing.JPanel jp_PlayMenu;
    private javax.swing.JPanel jp_SkillDesc;
    private javax.swing.JPanel jp_changeAcc;
    private javax.swing.JTextArea jta_DescriptionBody;
    private javax.swing.JTextArea jta_DescriptionBody_SP;
    // End of variables declaration//GEN-END:variables

    public void mouseClicked(MouseEvent e) {
        for(int i = 0; i < card.length; i++){
            if(e.getSource() == card[i]){
                card[i].setBackground(Color.red);
            }
        }
    }

    public void mouseEntered(MouseEvent e) {
        if(e.getSource() == card[0]){
            card[0].setBackground(Color.red);
        }else if(e.getSource() == card[1]){
            card[1].setBackground(Color.red);
        }else if(e.getSource() == card[2]){
            card[2].setBackground(Color.red);
        }else if(e.getSource() == card[3]){
            card[3].setBackground(Color.red);
        }else if(e.getSource() == card[4]){
            card[4].setBackground(Color.red);
        }else if(e.getSource() == card[5]){
            card[5].setBackground(Color.red);
        }else if(e.getSource() == card[6]){
            card[6].setBackground(Color.red);
        }else if(e.getSource() == card[7]){
            card[7].setBackground(Color.red);
        }else if(e.getSource() == card[8]){
            card[8].setBackground(Color.red);
        }else if(e.getSource() == card[9]){
            card[9].setBackground(Color.red);
        }else if(e.getSource() == card[10]){
            card[10].setBackground(Color.red);
        }else if(e.getSource() == card[11]){
            card[11].setBackground(Color.red);
        }else if(e.getSource() == card[12]){
            card[12].setBackground(Color.red);
        }else if(e.getSource() == card[13]){
            card[13].setBackground(Color.red);
        }
    }

}
