/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mgw.main;

import mgw.gameplay.Player;

/**
 *
 * @author mejap
 */
public class StatusBarLeft extends javax.swing.JPanel {

    private Player player;
    /**
     * Creates new form StatusBar
     */
    public StatusBarLeft() {
        initComponents();
    }
    
    public void setPlayer(Player player)
    {
        this.player = player;
        jl_PlayerName.setText(player.user.username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_PlayerName = new javax.swing.JLabel();
        jp_HealthBarMax = new javax.swing.JPanel();
        jp_healthBar = new javax.swing.JPanel();
        jp_SkillPointBarMax = new javax.swing.JPanel();
        jp_SkillPointBar = new javax.swing.JPanel();

        jl_PlayerName.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jl_PlayerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_PlayerName.setText("jLabel1");

        jp_healthBar.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jp_healthBarLayout = new javax.swing.GroupLayout(jp_healthBar);
        jp_healthBar.setLayout(jp_healthBarLayout);
        jp_healthBarLayout.setHorizontalGroup(
            jp_healthBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp_healthBarLayout.setVerticalGroup(
            jp_healthBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jp_HealthBarMaxLayout = new javax.swing.GroupLayout(jp_HealthBarMax);
        jp_HealthBarMax.setLayout(jp_HealthBarMaxLayout);
        jp_HealthBarMaxLayout.setHorizontalGroup(
            jp_HealthBarMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_healthBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_HealthBarMaxLayout.setVerticalGroup(
            jp_HealthBarMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_HealthBarMaxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jp_healthBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jp_SkillPointBar.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jp_SkillPointBarLayout = new javax.swing.GroupLayout(jp_SkillPointBar);
        jp_SkillPointBar.setLayout(jp_SkillPointBarLayout);
        jp_SkillPointBarLayout.setHorizontalGroup(
            jp_SkillPointBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp_SkillPointBarLayout.setVerticalGroup(
            jp_SkillPointBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jp_SkillPointBarMaxLayout = new javax.swing.GroupLayout(jp_SkillPointBarMax);
        jp_SkillPointBarMax.setLayout(jp_SkillPointBarMaxLayout);
        jp_SkillPointBarMaxLayout.setHorizontalGroup(
            jp_SkillPointBarMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_SkillPointBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_SkillPointBarMaxLayout.setVerticalGroup(
            jp_SkillPointBarMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_SkillPointBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_PlayerName)
                        .addContainerGap(403, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jp_HealthBarMax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp_SkillPointBarMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jl_PlayerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_HealthBarMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_SkillPointBarMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_PlayerName;
    private javax.swing.JPanel jp_HealthBarMax;
    private javax.swing.JPanel jp_SkillPointBar;
    private javax.swing.JPanel jp_SkillPointBarMax;
    private javax.swing.JPanel jp_healthBar;
    // End of variables declaration//GEN-END:variables
}
