
import javax.swing.JFrame;
import java.awt.*;
import javax.swing.*;
public class Program extends javax.swing.JFrame {

    /**
     * Creates new form Program
     */
    public Program() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jp_Background = new javax.swing.JPanel();
        jp_mainMenu = new javax.swing.JPanel();
        jl_AccountName = new javax.swing.JLabel();
        jp_PlayButton = new javax.swing.JPanel();
        jl_Play = new javax.swing.JLabel();
        jp_DeckButton = new javax.swing.JPanel();
        jl_Deck = new javax.swing.JLabel();
        jp_HelpButton = new javax.swing.JPanel();
        jl_Help = new javax.swing.JLabel();
        jp_ChangeAccountButton = new javax.swing.JPanel();
        jl_ChangeAccount = new javax.swing.JLabel();
        jp_OptionButton = new javax.swing.JPanel();
        jl_Option = new javax.swing.JLabel();
        jl_logo = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_AccountName.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jl_AccountName.setForeground(new java.awt.Color(255, 255, 255));
        jl_AccountName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jl_AccountName.setText("welcome,ready");

        jp_PlayButton.setBackground(new java.awt.Color(0, 0, 0));
        jp_PlayButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jp_PlayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_PlayButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_PlayButtonMouseExited(evt);
            }
        });

        jl_Play.setBackground(new java.awt.Color(255, 255, 255));
        jl_Play.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_Play.setForeground(new java.awt.Color(255, 255, 255));
        jl_Play.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Play.setText("PLAY");

        javax.swing.GroupLayout jp_PlayButtonLayout = new javax.swing.GroupLayout(jp_PlayButton);
        jp_PlayButton.setLayout(jp_PlayButtonLayout);
        jp_PlayButtonLayout.setHorizontalGroup(
            jp_PlayButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
            .addGroup(jp_PlayButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jl_Play, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
        );
        jp_PlayButtonLayout.setVerticalGroup(
            jp_PlayButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
            .addGroup(jp_PlayButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_PlayButtonLayout.createSequentialGroup()
                    .addComponent(jl_Play)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jp_DeckButton.setBackground(new java.awt.Color(0, 0, 0));
        jp_DeckButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_DeckButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_DeckButtonMouseExited(evt);
            }
        });

        jl_Deck.setBackground(new java.awt.Color(255, 255, 255));
        jl_Deck.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_Deck.setForeground(new java.awt.Color(255, 255, 255));
        jl_Deck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Deck.setText("DECK");

        javax.swing.GroupLayout jp_DeckButtonLayout = new javax.swing.GroupLayout(jp_DeckButton);
        jp_DeckButton.setLayout(jp_DeckButtonLayout);
        jp_DeckButtonLayout.setHorizontalGroup(
            jp_DeckButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Deck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_DeckButtonLayout.setVerticalGroup(
            jp_DeckButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Deck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jp_HelpButton.setBackground(new java.awt.Color(0, 0, 0));
        jp_HelpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_HelpButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_HelpButtonMouseExited(evt);
            }
        });

        jl_Help.setBackground(new java.awt.Color(255, 255, 255));
        jl_Help.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_Help.setForeground(new java.awt.Color(255, 255, 255));
        jl_Help.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Help.setText("HELP");
        jl_Help.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jp_HelpButtonLayout = new javax.swing.GroupLayout(jp_HelpButton);
        jp_HelpButton.setLayout(jp_HelpButtonLayout);
        jp_HelpButtonLayout.setHorizontalGroup(
            jp_HelpButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Help, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_HelpButtonLayout.setVerticalGroup(
            jp_HelpButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Help, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jp_ChangeAccountButton.setBackground(new java.awt.Color(255, 255, 255));

        jl_ChangeAccount.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_ChangeAccount.setForeground(new java.awt.Color(0, 0, 0));
        jl_ChangeAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_ChangeAccount.setText("Change Account");

        javax.swing.GroupLayout jp_ChangeAccountButtonLayout = new javax.swing.GroupLayout(jp_ChangeAccountButton);
        jp_ChangeAccountButton.setLayout(jp_ChangeAccountButtonLayout);
        jp_ChangeAccountButtonLayout.setHorizontalGroup(
            jp_ChangeAccountButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_ChangeAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jp_ChangeAccountButtonLayout.setVerticalGroup(
            jp_ChangeAccountButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_ChangeAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jp_OptionButton.setBackground(new java.awt.Color(0, 0, 0));
        jp_OptionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jp_OptionButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jp_OptionButtonMouseExited(evt);
            }
        });

        jl_Option.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jl_Option.setForeground(new java.awt.Color(255, 255, 255));
        jl_Option.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Option.setText("OPTION");

        javax.swing.GroupLayout jp_OptionButtonLayout = new javax.swing.GroupLayout(jp_OptionButton);
        jp_OptionButton.setLayout(jp_OptionButtonLayout);
        jp_OptionButtonLayout.setHorizontalGroup(
            jp_OptionButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Option, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
        );
        jp_OptionButtonLayout.setVerticalGroup(
            jp_OptionButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_OptionButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jl_Option))
        );

        javax.swing.GroupLayout jp_mainMenuLayout = new javax.swing.GroupLayout(jp_mainMenu);
        jp_mainMenu.setLayout(jp_mainMenuLayout);
        jp_mainMenuLayout.setHorizontalGroup(
            jp_mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_mainMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jp_mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_mainMenuLayout.createSequentialGroup()
                        .addComponent(jp_ChangeAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_mainMenuLayout.createSequentialGroup()
                        .addComponent(jl_AccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jp_mainMenuLayout.createSequentialGroup()
                .addGroup(jp_mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jp_PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jp_OptionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jp_DeckButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jp_HelpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(84, 84, 84)
                .addComponent(jl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jp_mainMenuLayout.setVerticalGroup(
            jp_mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_mainMenuLayout.createSequentialGroup()
                .addGroup(jp_mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_mainMenuLayout.createSequentialGroup()
                        .addContainerGap(89, Short.MAX_VALUE)
                        .addComponent(jp_PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jp_DeckButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_mainMenuLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jl_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(30, 30, 30)
                .addComponent(jp_OptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jp_HelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_AccountName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_ChangeAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout jp_BackgroundLayout = new javax.swing.GroupLayout(jp_Background);
        jp_Background.setLayout(jp_BackgroundLayout);
        jp_BackgroundLayout.setHorizontalGroup(
            jp_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_mainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_BackgroundLayout.setVerticalGroup(
            jp_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_mainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 786, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp_Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jp_PlayButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_PlayButtonMouseEntered
        jp_PlayButton.setBackground(Color.white);
        jl_Play.setForeground(Color.black);
    }//GEN-LAST:event_jp_PlayButtonMouseEntered

    private void jp_PlayButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_PlayButtonMouseExited
        jp_PlayButton.setBackground(Color.black);
        jl_Play.setForeground(Color.white);
    }//GEN-LAST:event_jp_PlayButtonMouseExited

    private void jp_DeckButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_DeckButtonMouseEntered
        jp_DeckButton.setBackground(Color.white);
        jl_Deck.setForeground(Color.black);
    }//GEN-LAST:event_jp_DeckButtonMouseEntered

    private void jp_DeckButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_DeckButtonMouseExited
        jp_DeckButton.setBackground(Color.black);
        jl_Deck.setForeground(Color.white);
    }//GEN-LAST:event_jp_DeckButtonMouseExited

    private void jp_OptionButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_OptionButtonMouseEntered
        jp_OptionButton.setBackground(Color.white);
        jl_Option.setForeground(Color.black);
    }//GEN-LAST:event_jp_OptionButtonMouseEntered

    private void jp_OptionButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_OptionButtonMouseExited
        jp_OptionButton.setBackground(Color.black);
        jl_Option.setForeground(Color.white);
    }//GEN-LAST:event_jp_OptionButtonMouseExited

    private void jp_HelpButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_HelpButtonMouseEntered
        jp_HelpButton.setBackground(Color.white);
        jl_Help.setForeground(Color.black);
    }//GEN-LAST:event_jp_HelpButtonMouseEntered

    private void jp_HelpButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_HelpButtonMouseExited
        jp_HelpButton.setBackground(Color.black);
        jl_Help.setForeground(Color.white);
    }//GEN-LAST:event_jp_HelpButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame program = new Program();
                program.setVisible(true);

                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jl_AccountName;
    private javax.swing.JLabel jl_ChangeAccount;
    private javax.swing.JLabel jl_Deck;
    private javax.swing.JLabel jl_Help;
    private javax.swing.JLabel jl_Option;
    private javax.swing.JLabel jl_Play;
    private javax.swing.JLabel jl_logo;
    private javax.swing.JPanel jp_Background;
    private javax.swing.JPanel jp_ChangeAccountButton;
    private javax.swing.JPanel jp_DeckButton;
    private javax.swing.JPanel jp_HelpButton;
    private javax.swing.JPanel jp_OptionButton;
    private javax.swing.JPanel jp_PlayButton;
    private javax.swing.JPanel jp_mainMenu;
    // End of variables declaration//GEN-END:variables
}
